### PR TITLE
Updating the build scripts to supppot paths with spaces in the name

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/project-system/issues/3187.

FYI. @tmat, @davkean, @jaredpar

### CODE REVIEW

**Comment by tannergooding** [comment]
It appears there is something terribly broken with `/p:QuietRestore=true`, as including that parameter causes:
```
MSBUILD : error MSB1008: Only one project can be specified. [C:\Users\tagoo\.nuget\packages\RoslynTools.RepoToolset\1.0.0-beta-62615-02\tools\Build.proj]
C:\Users\tagoo\.nuget\packages\RoslynTools.RepoToolset\1.0.0-beta-62615-02\tools\Build.proj(152,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MS
Build.exe" /nodeReuse:false "C:\Users\tagoo\.nuget\packages\RoslynTools.RepoToolset\1.0.0-beta-62615-02\tools\Tools.proj" /bl:"D:\project system\artifacts\Debug\log\RestoreRepoTools.binlog" /nologo /m /v:quiet
/t:Restore /p:Configuration=Debug /p:CIBuild=False /p:RepoRoot=D:\project system\ /p:VersionsPropsPath=D:\project system\build\Versions.props /p:DotNetPackageVersionPropsPath= /p:BaseIntermediateOutputPath=D:\p
roject system\artifacts\toolset\Common /p:ExcludeRestorePackageImports=true /p:UsingPipeBuildPublishing=false" exited with code 1.
```

**Comment by tannergooding** [comment]
Also FYI. @Pilchie, @jasonmalinowski

**Comment by davkean** [comment]
The change looks good. Please separate commits next time, these are two very different things that you are fixing.

**Comment by tannergooding** [comment]
@davkean. See https://github.com/dotnet/roslyn-tools/issues/181

Quoting the args is fairly trivial, but there is another "blocker" which is that any path with a trailing slash is misinterpreted. For example: `/p:RepoRoot="D:\project system\"` gets weirdly interpreted by MSBuild and breaks the rest of the argument parsing.

The "easiest" fix from there is likely to ensure the trailing slash is removed from the `Exec` command and is instead appended by the props/targets files, where required.

**Pull request merged**
