### PR TITLE
Fix paths to pipelines on solution file

### PR DESCRIPTION
**Pull request by dmonroym**

### CODE REVIEW

**Comment by drewnoakes** [comment]
@dmonroym https://github.com/dotnet/project-system/pull/5298 is intended to fix this kind of thing. I'll merge it now.

**Comment by davidwengier** [comment]
How does that solve this?

**Comment by drewnoakes** [comment]
@davidwengier the shared project is supposed to include everything on disk without needing to edit the solution file (which is very disruptive when switching between branches/commits). If it's not achieving that we probably need to update the globs.

**Comment by davidwengier** [comment]
My mistake, it does do that, but only when the project is loaded. It doesn't respond to live changes on disk.

**Comment by davkean** [comment]
@davidwengier Neither does the solution.

**Pull request closed without merging**
