### PR TITLE
Merge dev16.0.x to master

### PR DESCRIPTION
**Pull request by davkean**
This is a complete merge of dev16.0.x to master including https://github.com/dotnet/project-system/issues/4121. This makes master a Dev16-only branch, which means that it will only be able to be F5'd on Dev16.

### CODE REVIEW

**Comment by jmarolf** [comment]
Spanish build failure appears to be related to https://github.com/dotnet/project-system/pull/4036

```ini
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5582,44): error MSB4023: No se pueden evaluar los metadatos del elemento "%(FullPath)". Los metadatos "%(FullPath)" del elemento no pueden aplicarse a la ruta de acceso "F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.xml". No se admite el formato proporcionado de la ruta de acceso. [F:\vsagent\2\s\src\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5582,44): error MSB4023: No se pueden evaluar los metadatos del elemento "%(FullPath)". Los metadatos "%(FullPath)" del elemento no pueden aplicarse a la ruta de acceso "F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.Editors\F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.xml". No se admite el formato proporcionado de la ruta de acceso. [F:\vsagent\2\s\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj]
    0 Advertencia(s)
    2 Errores
```

which translated to:

```ini
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5582,44): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.xml". Illegal characters in path. [F:\vsagent\2\s\src\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5582,44): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.Editors\F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.xml". Illegal characters in path. [F:\vsagent\2\s\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj]
    0 Warning(s)
    2 Errors
```

**Comment by jmarolf** [comment]
@davkean while the run definition says "Spanish," the VM it used was dictated by the contents of the `.vsts-dnceng.yml`, file which until recently, required that image to come from the `Hosted VS2017` pool.  The  `Hosted VS2017` pool only contains english images.  This this merge we remove the `Hosted VS2017` requirement and Spanish now runs against its default pool which contains spanish images:
image

**Comment by jmarolf** [comment]
Looking at the logs, the failure does look real. `FullPath` is being set to `F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\F:\vsagent\2\s\artifacts\Debug\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.xml` which contains a `:` symbol in the midlle, which is invalid.

Looks like its combining paths wrong for vb on Spanish machines.

```XML
  <Target
      Name="DebugSymbolsProjectOutputGroup"
      Returns="@(DebugSymbolsProjectOutputGroupOutput)"
      DependsOnTargets="$(DebugSymbolsProjectOutputGroupDependsOn)"/>

  <!--
    ============================================================
                                        DocumentationProjectOutputGroup

    This target performs population of the Documentation project output group.
    ============================================================
    -->
  <PropertyGroup>
    <DocumentationProjectOutputGroupDependsOn></DocumentationProjectOutputGroupDependsOn>
  </PropertyGroup>
  <ItemGroup Condition="'$(DocumentationFile)'!='' and '$(OutputType)' != 'winmdobj'">
    <DocumentationProjectOutputGroupOutput Include="@(DocFileItem->'%(FullPath)')">
      <FinalOutputPath>@(FinalDocFile->'%(FullPath)')</FinalOutputPath>
      <IsKeyOutput>true</IsKeyOutput>
      <TargetPath>@(DocFileItem->'%(Filename)%(Extension)')</TargetPath>
    </DocumentationProjectOutputGroupOutput>
  </ItemGroup>
  <ItemGroup Condition="'$(DocumentationFile)' != '' and '$(OutputType)' == 'winmdobj'">
    <WinMDOutputDocumentationFileItem Include="$(WinMDOutputDocumentationFile)" Condition="'$(WinMDOutputDocumentationFile)' != ''" />
    <WinMDExpFinalOutputDocItem Include="$(_WinMDDocFileOutputPath)" Condition="'$(_WinMDDocFileOutputPath)' != ''" />
    <DocumentationProjectOutputGroupOutput Include="@(WinMDOutputDocumentationFileItem->'%(FullPath)')">
      <FinalOutputPath>@(WinMDExpFinalOutputDocItem->'%(FullPath)')</FinalOutputPath>
      <TargetPath>@(WinMDOutputDocumentationFileItem->'%(Filename)%(Extension)')</TargetPath>
    </DocumentationProjectOutputGroupOutput>
  </ItemGroup>
```

**Comment by jmarolf** [comment]
Invoking @nguerrera 

?: Do you know where the path combination logic for xml documentation files lives in the SDK?

**Comment by davkean** [comment]
Is this the bug they fixed?

**Comment by jmarolf** [comment]
@davkean 	I don't know but the bin log does not appear to have any info on how this path is calculated

**Comment by davkean** [comment]
This is using version 2.1.201 of the SDK. I cannot find a way to map SDK versions to VS versions but I assume this is an earlier version of VS on the spanish images. I have no idea how any of this works, I thought the pools used to list the stuff they had on the box, but the spanish pool does not.

**Comment by nguerrera** [comment]
2.1.2xx is 15.6

**Comment by davkean** [comment]
Okay, I understand what you were saying @jmarolf. We changed the set of pools we were running in in the dev16.0.x branch and we getting away with running Spanish images on 15.6. Now that we've merged that change to master, its met the code that hit the bug - and now we're not getting away with running on older version of VS/SDK.

How do we get later versions of VS onto the Spanish image?

**Comment by jmarolf** [comment]
I've pushed an update that bootstraps the version of the .NET Core SDK we use on CI builds.  This caused all unit test runs to pass.  I expect `windows_integration_debug` to fail as we do not have compatible images.  @davkean 	do you have any problems removing the `Required` check for integration tests in master and merging this PR?

**Comment by davkean** [comment]
Until we have integration tests that pass, we should just stop running them.

**Comment by jmarolf** [comment]
@davkean I am fine making that change

**Comment by jmarolf** [comment]
@davkean I have removed integration tests as a requirement to merge and will submit a PR against 16.0.x to not run the Jenkins queue for them at all

**Comment by jmarolf** [comment]
see: https://github.com/dotnet/project-system/pull/4218

**Comment by jmarolf** [comment]
I am not going to merge this until I get a :+1: from @Pilchie or @davkean

**Comment by Pilchie** [comment]
👍 from me!

**Pull request merged**
