### PR TITLE
Fix changed project references not causing rebuild

### PR DESCRIPTION
**Pull request by davkean**
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/781913?src=WorkItemMention&src-action=artifact_link.

This was accidentally removed in 0ae2a36f.

### CODE REVIEW

**Comment by davkean** [comment]
@jjmew This is a regression and needs to be be a part of Preview 3.

**Comment by jmarolf** [comment]
We _really_ like this PR @davkean

**Comment by Pilchie** [comment]
This has been approved - we need to get an insertion going for it now. @jmarolf can you help with that?

**Comment by jmarolf** [comment]
Do we need a dummy pr or if it's already approved can we merge and use the real pr?

**Comment by davkean** [comment]
I've merged just use the real PR.

**Comment by jmarolf** [comment]
Yep confirmed with Kevin.  I'll tag Doug to approve it once its created

**Pull request merged**
