### PR TITLE
make verified files as lf and utf8

### PR DESCRIPTION
**Pull request by SimonCropp**
https://github.com/VerifyTests/Verify?tab=readme-ov-file#text-file-settings
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/project-system/pull/9498)

### CODE REVIEW

**Review by drewnoakes — APPROVED** [review]
Thanks very much Simon. We were hitting issues updating Verify and this might well be the reason. Will try and revive that PR once this merges.

**Comment by drewnoakes** [comment]
Bumping to latest Verify requires bumping xunit too, which is blocked in #9457. Will revisit in future.

**Comment by SimonCropp** [comment]
@drewnoakes  this PR doesnt bump verify. these settings work back several years with of Verify versions

**Comment by drewnoakes** [comment]
Understood. What I meant was that we had previously hit issues when trying to bump Verify (https://github.com/dotnet/project-system/pull/9056#issuecomment-1571178058).

We are currently seeing issues upgrading xunit (https://github.com/dotnet/project-system/pull/9457#issuecomment-2240820586). Once that is addressed, we can try updating Verify to the latest too.

Thanks again for the PR.

**Pull request merged**
