### PR TITLE
New integration test infrastructure

### PR DESCRIPTION
**Pull request by davkean**
This is the initial start of the new integration test infrastructure from myself and @drewnoakes, biggest changes from previous:

- Logic has been moved from build.ps1 -> msbuild
- We reuse VSIX deployment that occurs during the build, where as previously we'd uninstall/reinstall the VSIXes
- The logic has been simplified, less copying files around, no more "mstest deployment" - everything just runs from output location and results are output directly to where we want them.
- The integration test logic is tied to a project, similar to how build/test already works. It makes the logic much simpler as we can reuse all the evaluation state of the build.
- Integration tests can now be run multiple times in a row 
- A new VS instance no longer crashes if you run them while VS is open
- VS is no longer torn down while if you run them while it is open
~- Settings are no longer thrown away after they are run~ This still seems to be occuring
- The output is much quieter with less noise being output to the console.

The current state of these tests are ready for "personal run" but not CI runs. CI run logic is being tracked by : https://github.com/dotnet/project-system/issues/5092.

Questions for @jmarolf:

- What is suite.json used for? See commit #2c594a96.
- Why do we need to convert TRX -> xUnit?

### CODE REVIEW

**Comment by jmarolf** [comment]
> What is suite.json used for? See commit #2c594a96.

this file is needed if you want to insert these tests as a nupkg at VS insertion time and run them against the VS you are insertion against.  This would allow other teams in VS to run our integration tests. For example, if we ran our tests on all PR in VS and if an SDK insertion would break project system the insertion PR would fail. That was the idea at least. This infrastructure on the VS side appears to have changed and this file is no longer needed? [here](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?pagePath=%2FEngineering%20System%20%26%20Tools%2FTest%20Docs%2FIntegration%20Tests%2FTest%20Run%20Authoring%2FTools%2FTest%20Deployment&pageId=884&wikiVersion=GBwikiMaster) is the latest documentation on how test assets need to be organized.

**Comment by jmarolf** [comment]
> Why do we need to convert TRX -> xUnit?

Once upon a time there was a desire to track test result statistics across all of github.com/dotnet. From the latest meetings it looks like this tracking requires arcade now so there is no point.

**Comment by davkean** [comment]
We're merging this in, this state is good for personal integration test execution.

Devs can run this via:

```
build /integrationtests
```
-or-
```
Microsoft.VisualStudio.ProjectSystem.IntegrationTests>msbuild /t:IntegrationTest
```

**Pull request merged**
