### PR TITLE
Set the Generate XML Documentation property correctly.

### PR DESCRIPTION
**Pull request by melytc**
Fixes the feedback ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1773467

This PR handles the scenario where there is no value to recover and set the `unevaluatedPropertyValue` as the value. I also followed the non-configurable setting that C# has for the same property, but I'm also okay leaving it configurable.

Before: you cannot set the property.
generate-xml-doc-property-bug

After: you can set the property and see it in the project file.
generate-xml-doc-property-fix

Open to discuss: do we want to also bring in the `DocumentationFile` property over to the VB Build property page, so the user sets it. It does have a comment saying that we wanted to remove that property all together, but I'm unsure the reason behind it. https://github.com/dotnet/project-system/blob/18ee5d2985bb0b7f438945f829ff9abf0bbbbbbe/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/Rules/PropertyPages/BuildPropertyPage.xaml#L315-L320

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8944)

### CODE REVIEW

**Review by MiYanni — COMMENTED** [review]
It seems like this feature isn't fully fleshed out. Very briefly looking over the SDK properties, there are 3 that seem to relate directly with this feature:
- [GenerateDocumentationFile](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generatedocumentationfile)
  - Boolean. This turns on/off generating the documentation XML file.
- [DocumentationFile](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#documentationfile)
  - String. This sets the path for the documentation file to be generated as.
- [PublishDocumentationFile](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#publishdocumentationfile)
  - Boolean. When generation is enabled, this will set if the generated documentation also goes to the Publish target output.

To use this feature completely, I'd recommend we have these 3 options for it. Only being able to turn it on/off is the bare minimum usability.

**Comment by melytc** [comment]
I've added the `DocumentationFile` property. This means that we have localization changes; loc freeze has passed, so I'll wait to consider merging this until main changes to be 17.7 next week.

**Review by drewnoakes — APPROVED** [review]

**Review by haileymck — APPROVED** [review]

**Comment by melytc** [comment]
I've added the three publishing properties, here's what it looks like:
doc-file-properties

And both the bin and obj folders have the generated file:
image

**Review by MiYanni — APPROVED** [review]

**Pull request merged**
