### PR TITLE
Add mnemonics to debug page.

### PR DESCRIPTION
**Pull request by melytc**
As noted in #5797, Debug page was missing the key accelerators, or mnemonics.

Visual Studio has already defined some menu mnemonics:
screenshot_vs_menubar

To avoid overlaps, I eliminated the letters _B, D, E, F, H, N, P, S, T, V, W, X_ from the set. I was able to assign a key accelerator to the majority of the properties, as shown below.

**Before:**
screenshot_before

**After:**
screenshot_after

You'll notice that buttons have no key accelerator assigned: I was left with 4 unique letters _(J, K, M, O)_ for the 6 different buttons. Any suggestion?

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6350)

### CODE REVIEW

**Comment by tmeschter** [comment]
What happens if two controls have the same accelerator? Does pressing that accelerator toggle between them? If so that _might_ be an acceptable solution, though you probably want to run it by the Accessibility champ.

**Comment by melytc** [comment]
> What happens if two controls have the same accelerator? Does pressing that accelerator toggle between them? If so that _might_ be an acceptable solution, though you probably want to run it by the Accessibility champ.

Just found it does work, thanks! (But only within the properties page, not with the VS menu) 
I'll ask an a11y champ to confirm that experience is okay and add it to the PR.

**Comment by drewnoakes** [comment]
Looks like "Executable" needs a mnemonic as well.

image

**Comment by melytc** [comment]
> Looks like "Executable" needs a mnemonic as well.
> 
> image

Good catch, I'll add it in my next commit.

Small update: I talked with Dante, an accessibility champ and he gave me great guidelines; like it's better to have buttons with unique accelerators, and accelerators are scoped (so it's okay to reuse one from the VS top level menu). I'll make some changes to better follow these.

**Comment by melytc** [comment]
Latest change:
image

**Pull request merged**
