### PR TITLE
Bump compiler to 3.8.0-4.20464.1

### PR DESCRIPTION
**Pull request by drewnoakes**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6619)

### CODE REVIEW

**Review by davkean — APPROVED** [review]

**Comment by davkean** [comment]
I'll close mine in in lieu of this: https://github.com/dotnet/project-system/pull/6611.

**Comment by drewnoakes** [comment]
Oh, missed yours. Should we be removing the `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json` feed though? If so, then merge yours over this.

**Comment by davkean** [comment]
I removed it because we don't pull the compiler from it anymore.

**Review by tmeschter — APPROVED** [review]

**Review by jjmew — APPROVED** [review]
:shipit:

**Pull request merged**
