### PR TITLE
Bump version number to 17.9

### PR DESCRIPTION
**Pull request by tmeschter**
The `main` branch is now targeting 17.9; update the version.json accordingly.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9283)

### CODE REVIEW

**Review by haileymck — APPROVED** [review]

**Comment by melytc** [comment]
should we also update the fabricbot.json file? so that PRs are marked with an updated milestone?

**Comment by smitpatel** [comment]
Also related changes in project-system-vscode.

**Comment by tmeschter** [comment]
> should we also update the fabricbot.json file? so that PRs are marked with an updated milestone?

That's on the to-do list (#9282).

**Comment by smitpatel** [comment]
Interesting that version number change requires new packages ingestion.

**Comment by tmeschter** [comment]
@smitpatel The failures seem to be around authentication, not ingestion.

**Review by drewnoakes — APPROVED** [review]

**Pull request merged**
