### PR TITLE
LOC CHECKIN | project-system dev15.6.x | 20180215

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by Pilchie** [comment]
@tmeschter - can you take a look at this?  It contains translations for @TIHan's new move commands, but doesn't contain them for @BillHiebert's new strings.

**Comment by tmeschter** [comment]
@Pilchie Aren't these @BillHiebert's new strings? https://github.com/dotnet/project-system/pull/3265/files#diff-652ef5f101e378c96c6741fc16ca405c

**Comment by Pilchie** [comment]
Uh, yes.  I just didn't read far enough down to see them.  😊

**Comment by tmeschter** [comment]
@Pilchie @BillHiebert Merged.

**Comment by Pilchie** [comment]
@natidea we'll need another insertion of this for 15.6.

@tmeschter - can we get a similar change for 15.5 with the same strings for the dialog that @BillHiebert added?

**Comment by tmeschter** [comment]
@natidea The VSO bug tracking this is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/566927.

**Pull request merged**
