### PR TITLE
Fix class libraries should not appear in startup projects.

### PR DESCRIPTION
**Pull request by ocallesp**

### CODE REVIEW

**Comment by davkean** [comment]
Didn't @drewnoakes fix this via https://github.com/dotnet/project-system/pull/7429?

**Comment by drewnoakes** [comment]
> Didn't @drewnoakes fix this via https://github.com/dotnet/project-system/pull/7429?

Yes, that was for 17.0. This is 16.11.

**Comment by drewnoakes** [comment]
@ocalles were you able to test this locally in the end?

**Comment by ocallesp** [comment]
@drewnoakes 
After the reset of the experimental instance I can it works.... 

image

**Review by MiYanni — APPROVED** [review]

**Comment by ocallesp** [comment]
Tested with 
ASP.NET  ---  F5, and Ctrl+5
and other projects  -- F5, and Ctrl+F5
Class library -- should not do F5
image

**Pull request merged**
