### PR TITLE
LOC CHECKIN | dotnet/project-system-master | 20171201

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by Pilchie** [comment]
@davkean didn't you delete the ConfigurationGeneralFile.xaml.cs.xlf files, because we didn't need them anymore?

**Comment by davkean** [comment]
Yes, either rerun this against current bits or manually delete all the ConfigurationGeneralFile.xaml.*.xlf files.

**Comment by nguerrera** [comment]
I've deleted the files in #3015

**Comment by nguerrera** [comment]
@Pilchie I've somehow lost permission to close issues or push to project-system.

**Comment by davkean** [comment]
@nguerrera For some reason you aren't on the Roslyn team: https://github.com/orgs/dotnet/teams/roslyn/members?utf8=%E2%9C%93&query=

**Pull request closed without merging**
