### PR TITLE
Remove SDK references from tests

### PR DESCRIPTION
**Pull request by davkean**
Works around https://github.com/Microsoft/msbuild/issues/2997.

This was supposed to be this: https://github.com/dotnet/project-system/pull/3334 - but accidentally merged into master instead of dev15.7.x.

### CODE REVIEW

**Comment by jeffkl** [comment]
The stack trace shows a class that does not exist anymore.  Are you sure the tests are using the correct MSBuild assemblies?

**Comment by davkean** [comment]
@jeffkl Regardless of whether we're using older or newer assemblies, why is the VS installation breaking the tests?

**Comment by jeffkl** [comment]
I don’t know. I need more info. I can’t repro it

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Pull request merged**
