### PR TITLE
Fixing the tab order on a number of the property pages

### PR DESCRIPTION
**Pull request by tannergooding**
**Customer scenario**

Users who rely on the keyboard to navigate VS may find the experience confusing
Users who rely on the narrator may not be able to navigate the property pages successfully

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems?id=441161&triage=true&_a=edit

**Workarounds, if any**

None

**Risk**

Minimal, this just changes the order in which controls gain focus via keyboard navigation

**Performance impact**

None

**Is this a regression from a previous update?**

No

**Root cause analysis:**

Known accessibility bug

**How was the bug found?**

Accessibility Tenant

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @dotnet/project-system, @dpoeschl 

This is the initial set of changes. I still have to validate
```
AddImportsDialogs\AutoAddImportsCollisionDialog
AddImportsDialogs\AutoAddImportsExtensionCollisionDialog

DesignerFramework\ErrorControl

MyExtensibility\AddMyExtensionsDialog
MyExtensibility\AssemblyOptionDialog
MyExtensibility\MyExtensibilityPropPage

package\EditorToolsOptionsPanel

PropPages\WPF\AppDotXamlErrorControl
PropPages\WPF\ApplicationPropPageVBWPF
PropPages\AdvCompilerSettingsPropPage
PropPages\ApplicationPropPageVBWinForms
PropPages\compileproppage2
PropPages\PackagePropPage
PropPages\ReferencePropPage
PropPages\ServicesAuthenticationForm
PropPages\UnusedReferencePropPage

ResourceEditor\DialogQueryName
ResourceEditor\OpenFileWarningDialog
ResourceEditor\ResourceEditorView

SettingsDesigner\SettingsDesignerView
SettingsDesigner\TypeEditorHostControl
SettingsDesigner\TypePickerDialog

XmlToSchema\InputXmlForm
XmlToSchema\PasteXmlDialog
XmlToSchema\WebUrlDialog
```

**Comment by srivatsn** [comment]
Is this ready?

**Comment by tannergooding** [comment]
@Srivatsn, there are still some more pages for me to follow up on, but there is no reason why this cannot go in as-is.

**Comment by srivatsn** [comment]
Let's get all the changes in together.

**Comment by tannergooding** [comment]
This should be ready to review now.

**Comment by tannergooding** [comment]
FYI. @MattGertz for AskMode approval

**Pull request merged**
