### PR TITLE
In-product acquisition proposal

### PR DESCRIPTION
**Pull request by cartermp**
https://github.com/dotnet/project-system/issues/6080

This still needs a lot of work, mostly in getting some mockups in there. But the set of applicable scenarios should mostly be listed.

Please consider this more as a proposal than a spec. Almost everything here is _proposed_ - I'm not tied to a particular scenario or way to do things (e.g., preferring to suggestion workloads over components if possible). It could also be that some of what I'm proposing here isn't feasible. We'll need to suss that out over time as the work actually happens.

The main thing here should be ensuring that we have adequate acquisition scenario coverage. If the rest of the doc should just get chopped to just that I'm happy to do that too.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6134)

### CODE REVIEW

**Comment by davkean** [comment]
tag @davidwengier

**Comment by davidwengier** [comment]
Just to confirm the scope of this, not all of the project types mentioned use the .NET Project System. eg, pre-net5 Xamarin and UWP are both legacy projects, and C++/CLI is the C++ project system.

**Comment by cartermp** [comment]
Re: Xamarin - not necessarily. You can create .NET Standard projects that reference Xamarin.Forms and act as core UI libraries today: https://github.com/xamarin/Essentials/blob/develop/Samples/Samples/Samples.csproj - while it's unlikely that someone has created/opened one of these things _without_ the head projects that use legacy projects (which then kick off current IPA), it's still possible. I can clarify that.

Re: C++/CLI - since they use CPS it could conceivably work, yes? Though scoping that out is something I'm certainly fine with

**Comment by dmonroym** [comment]
@cartermp can we merge this PR and maintain the discussion on https://github.com/dotnet/project-system/issues/6080?

**Comment by cartermp** [comment]
Yeah, I think this is merge-able for now. The design might change for .NET 6 but for now it's accurate in terms of what we _need_ to support.

**Pull request merged**
