### PR TITLE
Run PR build for each PR

### PR DESCRIPTION
**Pull request by smitpatel**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9160)

### CODE REVIEW

**Review by haileymck — APPROVED** [review]

**Comment by drewnoakes** [comment]
Why is this needed? There's no context here.

**Comment by smitpatel** [comment]
> Why is this needed? There's no context here.

We discussed during meeting today that we are enabling PR build for all PRs.

**Comment by drewnoakes** [comment]
Wasn't that what always happened? My understanding is that the previous configuration would run PR builds for any PR targeting branches `main`, `dev*`, `feature*`. I guess I'd like to understand what specific problem this PR addresses?

> We discussed during meeting today

It's good to write the context down in commits/PRs so that in future when we wonder why this change was made there's a written record.

**Comment by smitpatel** [comment]
The earlier configuration build PRs against main (the main build), dev* which is earlier release branches and feature* which is dedicated branch created for feature. This required that PR must be directly targeted at one of those branches.

When working on large feature, breaking it in parts is helpful in reviewing PR and understanding latter why particular change was happen based on commit. Reviewing individual commit in multi-commit PR is not as good as reviewing PR in github UI. If you decide to create separate PR for chunk of work (would mostly be single commit but can have more than one commit too in order to address feedback), it makes reviewing better. But because we had PR config rules, the base branch must be one of those. So only 1 PR at a time can exist (assuming targeting a feature branch). This change allows that any PR regardless of base branch will be built in our CI. So if a dev has PR for first part of work targeting main/feature branch, while they await on review on that PR, they can start working in next task and submit PR for that targeting the branch of first PR, and so on. Our current config didn't allow to build PRs targeting other branches in repo.

Recent example was https://github.com/dotnet/project-system/pull/9149
I have PR out for review about CFS. Moving to CFS allowed us to also use CPM (by removing requirement of source mapping), I submitted PR for it but kept it separate because they were different tasks, but it targeted CFS branch since that was necessity work. And because of this CPM changes PR didn't build till earlier PR was merged and base changed to main.

**Comment by drewnoakes** [comment]
Thanks that make a lot of sense. The change here allows us to file a PR against a PR branch.

Does this work in forks too? If I create a PR from my fork, and you submit a PR against the branch in my fork, will the build run? Historically in this repo we've all worked in forks.

**Comment by smitpatel** [comment]
I thought about forks.
A PR against a branch in a fork actually lives in forked repository rather than here. Afaik, all the forks would have their own build system. (We wouldn't want someone who forked repo to run build in our system). So probably PRs in forked repositories wouldn't work either.

**Pull request merged**
