### PR TITLE
Add TFMs to top level package properties grid (partial fix for 587 for RTM)

### PR DESCRIPTION
**Pull request by abpiskunov**
**Customer scenario**

Since we can not do full support for showing multiple TFMs in UI in RTM, we aggreed to show TFMs for top level packages in the properties grid separated by ';'

**Bugs this fixes:**

related to https://github.com/dotnet/roslyn-project-system/issues/587 

**Workarounds, if any**

N/A

**Risk**

Low

**Performance impact**

none

### CODE REVIEW

**Comment by abpiskunov** [comment]
@srivatsn in case you get this approved here is a change...

**Comment by abpiskunov** [comment]
@natidea @dotnet/project-system

**Comment by srivatsn** [comment]
Let's retarget this to post-dev15. This was rejected as a bar-check.

**Comment by davkean** [comment]
@abpiskunov Is this relevant anymore?

**Comment by abpiskunov** [comment]
No, after we check in  https://github.com/dotnet/project-system/pull/1880 these properties would be not needed, i will close it for now.

**Pull request closed without merging**
