### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by drewnoakes**
A Netflix by-product, from one night last week.

Changes are only in comments and documentation, and only to items in neither US nor British dictionaries.

### CODE REVIEW

**Comment by drewnoakes** [comment]
> cancelled vs canceled 

Hmm, maybe the British English dictionary didn't work. I didn't know this particular spelling was a regional difference.

**Comment by Pilchie** [comment]
I'm not sure if it's regional as much as just having multiple accepted spellings.

**Comment by tmeschter** [comment]
@drewnoakes Did you use a tool to find the misspellings, or did you just read a lot of comments? :-)

**Comment by drewnoakes** [comment]
> Did you use a tool to find the misspellings, or did you just read a lot of comments? :-)

@tmeschter rumours of my proofreading abilities have been greatly exaggerated.

R# has an extension for this (ReSpeller) which has just been merged into the main product as a first class feature of the extension.

**Comment by Pilchie** [comment]
Like I said - I'm totally fine with all the proposed changes :)

**Comment by davidwengier** [comment]
I once had a customer threaten to stop using enterprise software because a label said "enrolment" instead of "enrollment". English is hard.

**Comment by davkean** [comment]
@dotnet-bot retest windows_integration_debug please

**Pull request merged**
