### PR TITLE
LOC CHECKIN | dotnet/project-system master | 20190321

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by jmarolf** [comment]
looks like the xlf is out of date

```cmd
Build FAILED.

C:\Users\VssAdministrator\.nuget\packages\xlifftasks\0.2.0-beta-000081\build\XliffTasks.targets(90,5): error : 'AddImportsDialogs\xlf\AddImports.cs.xlf' is out-of-date with 'AddImportsDialogs\AddImports.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. [D:\a\1\s\src\Microsoft.VisualStudio.Editors\Microsoft.VisualStudio.Editors.vbproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by janbaltus** [comment]
I can see no diff other than target tag and also some change in Notes section.
Are there more details about error?

**Comment by davkean** [comment]
The error indicates that between something/someone taking a snapshot of the things to localize and this PR, the set of things to localize has changed. If you run build.cmd in the root from a Visual Studio Command Prompt, this will fix the issue.

**Comment by tmeschter** [comment]
Closing as this PR doesn't actually change any files.

**Pull request closed without merging**
