### PR TITLE
Fixing a couple of accessibility bugs in the property pages.

### PR DESCRIPTION
**Pull request by tannergooding**
Resolves VSO Bug 391341 and 391539

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @dpoeschl, @dotnet/project-system

**Comment by basoundr** [comment]
You will need to run https://github.com/nguerrera/xliff-converter to get the loc changes as well.

**Comment by dpoeschl** [comment]
I had no clue that was a thing.

**Comment by tannergooding** [comment]
@basoundr, I thought we were doing that once this time around, just before handoff?

**Comment by dpoeschl** [comment]
Paging @nguerrera in case he knows.

**Comment by basoundr** [comment]
Yes, now I remember having that conversation.

**Pull request merged**
