### PR TITLE
Bump VSSDK build tools package

### PR DESCRIPTION
**Pull request by drewnoakes**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8624)

### CODE REVIEW

**Review by MiYanni — COMMENTED** [review]
Seems this change causes the packages to no longer contain the `.clientenabledpkg` files. Not sure if those are necessary.

**Comment by drewnoakes** [comment]
I'm pretty sure those `.clientenabledpkg` files aren't needed any more. Will update the PR. @tmeschter any concerns?

**Comment by drewnoakes** [comment]
I'll follow up with the VSSDK folks to ensure the behaviour change is expected.

**Comment by tmeschter** [comment]
If things are otherwise working, no concerns.

**Review by tmeschter — APPROVED** [review]

**Pull request merged**
