### PR TITLE
Inline type DependencyNodeInfo

### PR DESCRIPTION
**Pull request by drewnoakes**
Only the ID property was used.

### CODE REVIEW

**Comment by jmarolf** [comment]
@drewnoakes 	can we please not merge things until the tests run please?

**Comment by drewnoakes** [comment]
@jmarolf I thought the tests had run. It was 90 minutes since the push, and the indicators were green. What did I miss?

**Comment by jmarolf** [comment]
Looks like an infra issue that the tests weren't started but the green check was just to indicated the license check was green

image

No validation of this change was done

**Comment by jmarolf** [comment]
Actually this is a bug in github that it doesn't show status after merge.  You are fine :)

**Comment by jmarolf** [comment]
Now the `Checks` tab will show the status of the last run

**Pull request merged**
