### PR TITLE
Revert change

### PR DESCRIPTION
**Pull request by etbyrd**
Was working on creating a PR to add my License fix to the dev16.0.x branch and accidentally pushed to the branch.

I apologize - I updated my remotes and this won't happen again.

### CODE REVIEW

**Comment by Pilchie** [comment]
It is.  I'll protect the 16.0 branch.

The other thing I tend to do is `git remote set-url --push upstream no_push`.  (Assuming your upstream is called that.  Might also be `dotnet` or whatever.   This makes it so that the push url doesn't resolve and pushes fail.

**Comment by drewnoakes** [comment]
Ethan and I set the push URL for his upstream remote to gibberish a few minutes back :)

So we have to remember to enable this protection on new branches in future too?

**Comment by Pilchie** [comment]
Yes :(  There doesn't seem to be rule templates.  `dev15.0.x` and `dev15.9.x` already had PR required, but `master` and `dev16.0.x` didn't.

@jmarolf / @davidwengier do we have docs on setting up new branches?  Can this be added to them?

**Comment by drewnoakes** [comment]
I don't see any difference in config between `master`,  `dev15.0.x`, `dev15.9.x`, or `dev16.0.x` branches.

This looks like the setting to use, with an empty list of users.

image

Actually the branch config seems to be rule based. Perhaps it's possible to set this up on all branches with a single rule. Do we ever need to push directly to branches?

**Comment by Pilchie** [comment]
> I don't see any difference in config between master, dev15.0.x, dev15.9.x, or dev16.0.x branches.

That's because I already changed them.

My read was that this option covered it...

image

**Comment by Pilchie** [comment]
But - I guess I missed the "and submitted via pull request"...

**Comment by drewnoakes** [comment]
We can set this up for all branches with a wildcard rule if we want to.

image

**Comment by drewnoakes** [comment]
@Pilchie I think you're right. That looks like a better setting.

**Comment by Pilchie** [comment]
Changed to a single `*` rule with both for now.  We will see if it breaks everything ;)

**Comment by drewnoakes** [comment]
Created #4643 to track this.

**Comment by drewnoakes** [comment]
So to test this out I just pushed a new branch `integration-tests` which I now cannot delete :)

**Comment by drewnoakes** [comment]
I had to delete the rule in order to delete the branch. So a downside of this approach is that you can create a branch, but not delete it.

**Pull request merged**
