### PR TITLE
 Fix hang in language service integration when latter evaluation occurs before design-time build 

### PR DESCRIPTION
**Pull request by davkean**
This includes https://github.com/dotnet/project-system/pull/3346, so just review https://github.com/dotnet/project-system/commit/a1ce728734f6458fa2092d7444f5e79de7423cfc.

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/537755.

When evaluating in quick succession, Visual Studio can hang when attempting to throw away old evaluation results.

This can occur when AbstractEvaluationCommandLineHandler receives results in the following order:

1. Evaluation (Version 1)
2. Evaluation (Version 2)
3. Design Time Build (Version 1) <-- Hang attempting to throw away results from in step 1

It will continually loop the previous evaluations neither discarding them or breaking from the loop.

### CODE REVIEW

**Comment by davkean** [comment]
Read: https://github.com/dotnet/project-system/blob/7493e5bf96ce9c122912f379abbde26ef139d26c/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/Handlers/AbstractEvaluationCommandLineHandler.cs#L17 for background on how this logic works.

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_release please.

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_release please

**Comment by davkean** [comment]
@dotnet-bot retest this please - hitting the same hangs.

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Pull request merged**
