### PR TITLE
Mark command as client compliant

### PR DESCRIPTION
**Pull request by melytc**
This marks the 'Edit project file' command as client compliant.

Testing is **blocked**, not merging this to master yet.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6157)

### CODE REVIEW

**Comment by davkean** [comment]
Now that we know when and how commands will stop up, @tmeschter do we have a bug to change this code to use the real EditProjectFile command?

**Comment by tmeschter** [comment]
@melytc Do we need to add the .clientenabledpkg files that the CPS change has? E.g. in https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/240597.

**Comment by melytc** [comment]
@tmeschter I don't think so, looking at the [wiki](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/8735/How-to-mark-a-component-as-compliant-for-Nexus?anchor=mark-extensions-and-packages-as-compliant), I followed the `Extensions` steps rather than the `Legacy packages` ones. Let me confirm this.

**Comment by melytc** [comment]
@tmeschter, you're right, thanks!

**Comment by davidwengier** [comment]
So we're a legacy package _and_ and extension?

**Comment by melytc** [comment]
Talked with Ankit from the team leading this. We both misunderstood and we don't need that clientenabledpkg file, since we create an extension (vsix file) that includes the `extension.vsixmanifest` file, `.pkgdef` files and already a `.clientenabledpkg` file. 

Sorry for the confusion there, deleting that last commit :)

**Comment by dmonroym** [comment]
Tests have passed twice, they're not getting reported back correctly though: https://dev.azure.com/dnceng/public/_build/results?buildId=640251&view=results

**Pull request merged**
