### PR TITLE
Package Property Page Accessible Name Change

### PR DESCRIPTION
**Pull request by etbyrd**
Adds the Narrator fix for the Assembly Version as in [4054](https://github.com/dotnet/project-system/pull/4054)

### CODE REVIEW

**Comment by etbyrd** [comment]
@dotnet-bot retest please

**Comment by Pilchie** [comment]
This is the same as #4054 and #4055 isn't it?

**Comment by etbyrd** [comment]
Yes - The same fixes but proactively for a different property page.

**Comment by jmarolf** [comment]
closed and reopened to get the tests to run.

**Comment by etbyrd** [comment]
This PR no longer changes the Neutral Language combo box to the DropDownList style like in #4055 - I am working on a different way to fix that issue. 

We should still fix the Accessible Names on the Package Property page, and I will merge this when tests pass.

**Pull request merged**
