### PR TITLE
move project system to target .NET 4.7.2

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by jmarolf** [comment]
>We have a nuspec that needs to be updated as well, right?

This just flows natually from not using a nupec and having it be a part of the proejct

https://github.com/dotnet/project-system/blob/62e0cf178f5a1a7f387265de1d8e3422e6de1431/src/Microsoft.VisualStudio.ProjectSystem.Managed/Microsoft.VisualStudio.ProjectSystem.Managed.csproj#L9-L13


**Microsoft.VisualStudio.ProjectSystem.Managed**

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Microsoft.VisualStudio.ProjectSystem.Managed</id>
    <version>3.0.0-ci</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>http://go.microsoft.com/fwlink/?LinkId=529443</licenseUrl>
    <projectUrl>https://github.com/dotnet/roslyn-project-system</projectUrl>
    <description>Microsoft VisualStudio ProjectSystem for Managed languages Projects</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <tags>Roslyn Managed Project System VisualStudio</tags>
    <serviceable>true</serviceable>
    <repository url="https://github.com/dotnet/roslyn-project-system" />
    <dependencies>
      <group targetFramework=".NETFramework4.7.2">
        <dependency id="Microsoft.Build" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Engine" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.CodeAnalysis" version="2.11.0-beta1-63430-03" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Net.RoslynDiagnostics" version="2.6.1-beta1-62702-01" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.LanguageServices" version="2.11.0-beta1-63430-03" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ProjectSystem.Analyzers" version="16.0.201-pre-g7d366164d0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ProjectSystem.SDK" version="16.0.201-pre-g7d366164d0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Threading" version="15.8.145" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Validation" version="15.3.58" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
        <dependency id="RoslynTools.RepoToolset" version="1.0.0-beta-62705-01" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.Win32.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.AppContext" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Console" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Diagnostics.FileVersionInfo" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Diagnostics.Tracing" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Globalization.Calendars" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.Compression" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.Compression.ZipFile" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.FileSystem" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.FileSystem.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Linq" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Linq.Expressions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Net.Sockets" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Reflection" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.Extensions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.InteropServices" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.InteropServices.RuntimeInformation" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Algorithms" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Encoding" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.X509Certificates" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Text.RegularExpressions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.ValueTuple" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.ReaderWriter" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XmlDocument" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XPath" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XPath.XDocument" targetFramework=".NETFramework4.7.2" />
    </frameworkAssemblies>
  </metadata>
</package>
```


**Microsoft.VisualStudio.ProjectSystem.Managed.VS**


```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Microsoft.VisualStudio.ProjectSystem.Managed.VS</id>
    <version>3.0.0-ci</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>http://go.microsoft.com/fwlink/?LinkId=529443</licenseUrl>
    <projectUrl>https://github.com/dotnet/roslyn-project-system</projectUrl>
    <description>Microsoft VisualStudio ProjectSystem for Managed Languages Project hosts that interact with VisualStudio interfaces.</description>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <tags>Roslyn Managed Project System VisualStudio</tags>
    <serviceable>true</serviceable>
    <repository url="https://github.com/dotnet/roslyn-project-system" />
    <dependencies>
      <group targetFramework=".NETFramework4.7.2">
        <dependency id="Microsoft.VisualStudio.ProjectSystem.Managed" version="3.0.0-ci" exclude="Build,Analyzers" />
        <dependency id="EnvDTE" version="8.0.1" exclude="Build,Analyzers" />
        <dependency id="EnvDTE80" version="8.0.1" exclude="Build,Analyzers" />
        <dependency id="EnvDTE90" version="9.0.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Engine" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Utilities.Core" version="15.8.166" exclude="Build,Analyzers" />
        <dependency id="Microsoft.CodeAnalysis" version="2.11.0-beta1-63430-03" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Net.RoslynDiagnostics" version="2.6.1-beta1-62702-01" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VSDesigner" version="15.0.26606-alpha" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VSSDK.BuildTools" version="15.8.3252" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ComponentModelHost" version="15.0.26606" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.CoreUtility" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Data.Core" version="9.0.21022" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Data.Services" version="9.0.21022" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.DataTools.Interop" version="15.0.26606-alpha" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Designer.Interfaces" version="1.1.4322" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Diagnostics.PerformanceProvider" version="16.0.28226-alpha" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Editor" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.GraphModel" version="16.0.28226-alpha" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ImageCatalog" version="15.0.26606" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime" version="14.3.25408" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.LanguageServices" version="2.11.0-beta1-63430-03" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ManagedInterfaces" version="8.0.50727" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ProjectSystem.Analyzers" version="16.0.201-pre-g7d366164d0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.ProjectSystem.SDK" version="16.0.201-pre-g7d366164d0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.15.0" version="15.0.26606" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Design" version="15.0.26606" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Framework" version="16.0.28226-pre" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.10.0" version="10.0.30320" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.11.0" version="11.0.61031" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.12.1.DesignTime" version="12.1.30328" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime" version="14.3.25407" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.15.0.DesignTime" version="15.0.26932" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.15.3.DesignTime" version="15.0.26606" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.15.7.DesignTime" version="15.7.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Shell.Interop.9.0" version="9.0.30729" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Telemetry" version="15.3.799-masterDDDBA9E4" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Text.Data" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Text.Logic" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Text.UI" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Text.UI.Wpf" version="16.0.177-g0ae5fa46a1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.TextManager.Interop.10.0" version="10.0.30319" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.TextManager.Interop.12.0" version="12.0.30110" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.TextManager.Interop.12.1.DesignTime" version="12.1.30328" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Threading" version="15.8.145" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Threading.Analyzers" version="15.8.145" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Utilities" version="16.0.28226-pre" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.VSHelp" version="15.0.26606-alpha" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.Validation" version="15.3.58" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.WCFReference.Interop" version="9.0.30729" exclude="Build,Analyzers" />
        <dependency id="Microsoft.VisualStudio.XmlEditor" version="15.0.26606-alpha" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="9.0.1" exclude="Build,Analyzers" />
        <dependency id="NuGet.SolutionRestoreManager.Interop" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="NuGet.VisualStudio" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="RoslynTools.RepoToolset" version="1.0.0-beta-62705-01" exclude="Build,Analyzers" />
        <dependency id="VSLangProj" version="7.0.3300" exclude="Build,Analyzers" />
        <dependency id="VSLangProj100" version="10.0.30319" exclude="Build,Analyzers" />
        <dependency id="VSLangProj110" version="11.0.61030" exclude="Build,Analyzers" />
        <dependency id="VSLangProj158" version="15.8.0" exclude="Build,Analyzers" />
        <dependency id="VSLangProj2" version="7.0.5000" exclude="Build,Analyzers" />
        <dependency id="VSLangProj80" version="8.0.50727" exclude="Build,Analyzers" />
        <dependency id="VSLangProj90" version="9.0.30729" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.Win32.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.AppContext" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Console" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Diagnostics.FileVersionInfo" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Diagnostics.Tracing" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Globalization.Calendars" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.Compression" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.Compression.ZipFile" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.FileSystem" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.IO.FileSystem.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Linq" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Linq.Expressions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Net.Sockets" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Reflection" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.Extensions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.InteropServices" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Runtime.InteropServices.RuntimeInformation" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Algorithms" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Encoding" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.Primitives" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Security.Cryptography.X509Certificates" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Text.RegularExpressions" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.ValueTuple" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.ReaderWriter" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XmlDocument" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XPath" targetFramework=".NETFramework4.7.2" />
      <frameworkAssembly assemblyName="System.Xml.XPath.XDocument" targetFramework=".NETFramework4.7.2" />
    </frameworkAssemblies>
  </metadata>
</package>
```

**Comment by jmarolf** [comment]
However this dependency looks wrong:
```XML
<dependency id="RoslynTools.RepoToolset" version="1.0.0-beta-62705-01" exclude="Build,Analyzers" />
```

But that is orthogonal to this change.

**Comment by davkean** [comment]
You need the .NET Framework 4.7.2 _targeting pack_, not SDK.

**Comment by jmarolf** [comment]
@davkean 	yep, thats the correct terminology.  We need the targeting pack on the spanish machines for this to get merged.

**Comment by davidwengier** [comment]
Might not be relevant but building locally against a .NET 4.7.2 Roslyn build there are 8 files I had to update that variously had `TargetFramework`s of `net46`, `net461` and `net462`. Just thought I'd mention it in case you only did a search for one of those.

**Comment by davidwengier** [comment]
Further to the above, this is everything I had to do to get my local branch building against a 4.7.2 of Microsoft.VisualStudio.LanguageServices

https://github.com/davidwengier/project-system/commit/3a684f6934bd80a92d771801d0c6ada47207f357

**Comment by genlu** [comment]
@jmarolf Could you please also upgrade Roslyn references to pick up bits targeting 472 and verify everything still works?

**Comment by jmarolf** [comment]
@genlu 	which version of roslyn do you need us to target?

**Comment by genlu** [comment]
Any version that targets 472 would do, probably latest preview 2 bits? I just wanna make sure build would still work after both retargeted to 472.

**Comment by jmarolf** [comment]
Turning off spanish builds temporarily so we can move forward. tracking issue is: https://github.com/dotnet/project-system/issues/4309

**Pull request merged**
