### PR TITLE
Change the ProjectTemplate Packages that we drop into VS to NetCore 2.x 

### PR DESCRIPTION
**Pull request by srivatsn**
Today we drop the template NuGet packages for 1.x to VS so that if the CLI is not installed (Desktop or UWP workload) then VS can still find the netstandard templates. This is bumping up those templates to 2.x.

Instead of having the version in the VS component, I'm simply calling the component ProjectTemplates.Packages so that in the future we don't have to keep changing the component.

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz for 15.4:

**Customer scenario**

Creating a netstandard library without the CLI installed (UWP\Desktop workload) will create a 1.3 library instead of a 2.0 one.

**Bugs this fixes:** 
N/A

**Workarounds, if any**

Manually retarget.

**Risk**

Low. We are updating the template package

**Performance impact**

Low.

**Is this a regression from a previous update?**

Not a regression. 

**Root cause analysis:**

New planned work.

**Comment by nguerrera** [comment]
Does this mean the sdk in the legacy msbuild sdks path has to be 2.0?

**Comment by srivatsn** [comment]
Yes it does - otherwise it will show that error. Is that being updated?

**Comment by nguerrera** [comment]
No. It is not being updated. 2.0 sdk builds no longer produce the component. :(

**Comment by nguerrera** [comment]
Can we buy time by keeping the experience at ns 1.x for now. I don't think we can get 2.0 sdk at legacy path by tomorrow and I would like time to discuss the direction.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nguerrera** [comment]
I mean keeping it at 1.x so long as cli is not installed or not at version 2.0.

**Comment by davkean** [comment]
@nguerrera @nguerrera Is this still relevant?

**Comment by nguerrera** [comment]
It is not. We decided not to update the legacy location.

**Pull request closed without merging**
