### PR TITLE
Update CPS version

### PR DESCRIPTION
**Pull request by BillHiebert**
Update the referencedversion of CPS (and some dependent packages) to pick up a new launch target for use in C# Dev Kit

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9209)

### CODE REVIEW

**Review by smitpatel — APPROVED** [review]
Monitoring build in case need to ingest the packages. I will take care of ingestion if PR build fails.

**Comment by tmeschter** [comment]
@smitpatel I *think* I took care of  that (I restored Bill's change on my local system) but monitoring is appreciated. :-)

**Review by tmeschter — APPROVED** [review]

**Pull request merged**
