### PR TITLE
Add xaml rules to Setup Authoring

### PR DESCRIPTION
**Pull request by basoundr**
Over a period of time, some of the Xaml rules were forgetten to be added to the Setup Authoring and also forgotten to Localized.

The first commit just adds the changes performed by xliff-converter on the current state of the branch with none of my change.

The other commits add missing Xaml rules to Setup Authoring.

Fixes: [VSO 458744](https://devdiv.visualstudio.com/DevDiv/_workitems?id=458744)

**Customer scenario**

In some cases, changes to project references don't trigger a build as we assume that the project is uptodate. 

Some new XAML files were added that are needed for uptodate check for reference assemblies but weren't actually setup-authored. We didn't find this since F5 deploys these files correctly. 

**Bugs this fixes:** 

[VSO 458744](https://devdiv.visualstudio.com/DevDiv/_workitems?id=458744)

**Workarounds, if any**

Rebuild the solution everytime

**Risk**

Low since we are not adding any new functionality. We are just making setup authoring and localization changes here.

**Is this a regression from a previous update?**

Yes. The Setup authoring was not updated when we made the changes to support Ref assemblies for Up To Check

**Root cause analysis:**

Lack of Integration tests which we are working on.

**How was the bug found?**

Vendor created

@panopticoncentral @srivatsn @dotnet/project-system for review

fyi @balachir

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz - set PUTriage in https://devdiv.visualstudio.com/DevDiv/_workitems?id=458744&_a=edit

**Comment by davkean** [comment]
This is two different bugs, no?

**Comment by basoundr** [comment]
@davkean The issue is, a bunch of Xamls (and Localized Xamls)have not been included in the Setup Authoring. So we have Localized them and added to the Setup Authoring

**Comment by natidea** [comment]
Shiproom Approved to merge via [VSO 458744](https://devdiv.visualstudio.com/DevDiv/_workitems?id=458744)

**Comment by natidea** [comment]
@basoundr can we merge this?

**Comment by basoundr** [comment]
@natidea done :)

**Pull request merged**
