### PR TITLE
Do not deploy templates locally due to https://github.com/Microsoft/extendvs/issues/41

### PR DESCRIPTION
**Pull request by jmarolf**
Deploying template files as part of a VSIX can cause the root path to be very long
```
C:\Users\jmarolf\AppData\Local\Microsoft\VisualStudio\15.0_65f7540aRoslynDev\Extensions\Microsoft\C# .NETCore Project Templates\42.42.42.42
```

Add to that the fact that all templates need additional folders to specify their usage and you quickly run into max path issues 
```
ProjectTemplates\CSharp\.NET Core\1033\ClassLibrary-CSharp-NetCoreApp\ClassLibrary-CSharp-NetCoreApp.vstemplate
```

This disables deploying these templates on build until https://github.com/Microsoft/extendvs/issues/41 is fixed

fixes https://github.com/dotnet/project-system/issues/2098

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/project-system please review

**Comment by davkean** [comment]
Why don't we just make the file length shorter? What makes we say that Microsoft/extendvs#41 is going to be fixed?

**Comment by jmarolf** [comment]
@davkean Microsoft/extendvs#41 is a regression from 15.0, they may never fix it, but it used to work.

In this path we can changes "C# .NETCore Project Templates" and  "ClassLibrary-CSharp-NetCoreApp" to get us below 251
```
C:\Users\jmarolf\AppData\Local\Microsoft\VisualStudio\15.0_65f7540aRoslynDev\Extensions\Microsoft\C# .NETCore Project Templates\42.42.42.42\ProjectTemplates\CSharp\.NET Core\1033\ClassLibrary-CSharp-NetCoreApp\ClassLibrary-CSharp-NetCoreApp.vstemplate
```

changing them to `a` and `x` would still put us at 165
```
C:\Users\jmarolf\AppData\Local\Microsoft\VisualStudio\15.0_65f7540aRoslynDev\Extensions\Microsoft\a\42.42.42.42\ProjectTemplates\CSharp\.NET Core\1033\x\x.vstemplate
``` 

I am all ears for what a reasonable set of names should be used but my usual policy for when something doesn't handle max path is to remove it completly from the build system as there is no real way to win here.

**Comment by davkean** [comment]
165 is under the limit, what's wrong with that?

Not sure I understand the end game here - how do we test these templates if we don't deploy them?

**Comment by jmarolf** [comment]
@davkean I changed my mind here.  considering the template name counts twice toward the path name I've reduced that to get us under 250

**Pull request merged**
