### PR TITLE
Up to date check logs changed item info

### PR DESCRIPTION
**Pull request by drewnoakes**
This additional logging info will help debug certain situations such as that described in #6647.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6660)

### CODE REVIEW

**Comment by davkean** [comment]
Is this persisted between calls or just thrown away? ie Does this increase the footprint of this class?

**Comment by drewnoakes** [comment]
Thrown away and recreated on project load.

And yes there is overhead in keeping all these items in memory. However the strings are unchanged, so we're only paying for a densely packed array of:

```c#
(bool isAdd, string ItemType, string Path, string? Link, CopyType)
```

Rearranging this value tuple or making `CopyType : byte` may make it pack more efficiently.

**Comment by davkean** [comment]
Don't we keep the removed items? ie We're holding onto strings that would have otherwise been collected? Can we only capture this data if logging is on?

**Comment by drewnoakes** [comment]
> Don't we keep the removed items? ie We're holding onto strings that would have otherwise been collected?

How much of an issue is this in reality? It's rare to remove a large number of items, and those strings would be released upon the next change to the project's set of items anyway.

> Can we only capture this data if logging is on?

The logging setting can be changed dynamically. If we don't retain this data until logging is enabled, then when it's turned on we won't have the "before" data to diff against, which would appear as a bug.

**Comment by drewnoakes** [comment]
Ping @davkean

**Review by davkean — APPROVED** [review]

**Pull request merged**
