### PR TITLE
pulling down optprof data and using it in our build

### PR DESCRIPTION
**Pull request by jmarolf**
**Customer scenario**

We are seeing close solution take longer because the property pages are not optimized.  

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems?id=360010

**Workarounds, if any**

None

**Risk**

Minimal, this change is only about using the latest optprof data.

**Performance impact**

This should improve performance when these assemblies are ngen'd on install other than that there is no perf impact for assemblies that do not have optprof data.

**Is this a regression from a previous update?**

No but this is a regression from Dev14

**Root cause analysis:**

Optprof data was not setup for the project system repo

**How was the bug found?**

This was identified late in the cycle in a perf run

### CODE REVIEW

**Comment by jmarolf** [comment]
**NOTE:** I am in the process of updating the nuget package to contain optprof data for the editor assemblies.  This cannot be merged in until that work is completed.

**Comment by jmarolf** [comment]
@dotnet/project-system please review

**Comment by jmarolf** [comment]
retest all please

**Comment by jmarolf** [comment]
Validation build for this is [here](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=767258)

**Comment by srivatsn** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
Validation build has completed and it looks like we are good.  @srivatsn do we want to take this  for escrow?

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
retargeting for preview 3. @MattGertz for ask mode approval

**Pull request merged**
