### PR TITLE
Add project capability DynamicDependentFile

### PR DESCRIPTION
**Pull request by drewnoakes**
Now that WTE has inserted their opt-out logic, we can enable this.

//cc: @abpiskunov @jmarolf

### CODE REVIEW

**Comment by drewnoakes** [comment]
Fixes #159.

**Comment by abpiskunov** [comment]
👍

**Comment by davkean** [comment]
Is it required that this is a fixed (vs dynamic) capability? ie Is it deliberate that this in our project registration vs targets file?

**Comment by drewnoakes** [comment]
If this can be a dynamic dependency, do we need the CPS precedence order suppression logic for this? Can't we just add the capability dynamically, and WTE can turn it off? Can we make this all a bunch simpler?

**Comment by lifengl** [comment]
We can handle it dynamically.  You can try to add/remove it in the project file.

Sent from my phone

On Dec 12, 2018, at 4:54 PM, Drew Noakes <notifications@github.com<mailto:notifications@github.com>> wrote:


If this can be a dynamic dependency, do we need the CPS precedence order suppression logic for this? Can't we just add the capability dynamically, and WTE can turn it off? Can we make this all a bunch simpler?

**Comment by drewnoakes** [comment]
@lifeng thanks. Does this mean that if we add the capability then WTE can remove it again, and we end up in the same place without needing `SuppressLowerPriority` logic?

@abpiskunov would that work for you?

**Comment by drewnoakes** [comment]
Closing in favour of #4378.

**Pull request closed without merging**
