### PR TITLE
Dependency node integration tests

### PR DESCRIPTION
**Pull request by drewnoakes**
First cut of integration tests for the dependencies node. Relates to #1607.

These tests build up a solution/project(s)/global.json on disk, load the solution, then inspect the dependencies nodes.

See `DependencyNodeIntegrationTests` for how such tests are authored.

~🚧 Requires changes to Apex which have been merged but are not yet available via public package. This can be tested manually using the hand-built, unsigned package at \\mlangfs1\public\drnoakes~

### CODE REVIEW

**Comment by drewnoakes** [comment]
Thanks to @javierdlg for publishing my Apex changes via [myget](https://vside.myget.org/feed/vs-impl/package/nuget/Microsoft.Test.Apex.VisualStudio).

**Comment by jmarolf** [comment]
@drewnoakes resolve this build dependency issues and I think this looks good!

**Comment by jmarolf** [comment]
@drewnoakes please retarget to feature/integration-tests

**Comment by drewnoakes** [comment]
@jmarolf I just rebased on your branch. Let's see how this goes.

**Pull request closed without merging**
