### PR TITLE
Always use the loaded System.String in the ResX designer

### LINKED ISSUE #2512: Editing a resx file in a .NET Core 2.0 project crashes VS
Repro steps:
1. Create a .NET Core 2.0 console app
2. Add a resource file
3. Open it, edit it and save.

We had the same issue for .NET Standard projects and we put in a workaround in the resx designer (https://github.com/dotnet/project-system/pull/2355) that redirects requests for System.String, netstandard.dll to System.String, mscorlib.dll

For netcoreapp 2.0 projects, however, we get a request for System.String, System.Runtime, 4.2.0.0. That version of System.Runtime isn't in the closure of VS's search paths - so same problem different form.

Maybe the hack needs to be scoped differently and we should say if the request is for a System.String then return the one that's loaded. Given String seems to be only supported type for resx files in netcore projects.

### PR DESCRIPTION
**Pull request by tmeschter**
In a project targeting netstandard2.0 our multi-targeting support would quite correctly tell the ResX designer that System.String came from netstandard.dll. The designer would then try to load netstandard.dll, fail, and crash VS because netstandard.dll isn't part of the desktop 4.6.2 framework used by VS.

To work around this we redirected all types from netstandard.dll to mscorlib.dll. This turned out to be both overly broad and insufficient. Overly broad because System.String is the only type used by the designer that the multi-targeting service is going to redirect. And insufficient because in projects targeting netcoreapp2.0 System.String lives in System.Runtime version 4.0.2.0--and the desktop framework doesn't have that version of System.Runtime. So editing ResX files in these projects still led to a crash.

The fix here is to *only* redirect System.String, and *always* redirect it to whatever System.String is being used by VS. This works for projects targeting netstandard2.0 and netcoreapp2.0. I've also tested adding icons, image files, audio files, and text files (that is, everything you can add through the designer) and those work fine as well.

**Customer scenario**

Customer creates a new app targeting `netcoreapp2.0` and adds and opens a .resx file. When they attempt to add a new string resource, VS crashes.

**Bugs this fixes:** 

Fixes #2512.

**Workarounds, if any**

None.

**Risk**

Low

**Performance impact**

Low to none.

**Is this a regression from a previous update?**

Yes, in the sense that this just happened to work fine when targeting .NET Core 1.0.

**Root cause analysis:**

The resource editor has always assumed that the target framework was a subset of the framework being used by VS itself, and as such any type referenced by the .resx file could be found and loaded.

With .NET Standard and .NET Core this is no longer the case. .NET Standard 2.0 has System.String in netstandard.dll, which isn't available in the Desktop 4.6.2 framework. .NET Core 2.0 has System.String in a version of System.Runtime newer than the one in the Desktop 4.6.2 framework.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by davkean** [comment]
@tmeschter Does this burn in 4.0.0.0 into the RESX itself? Can you try targeting 3.5 and see if this effected by this?

Is Byte[] in the same bucket? (Choose Files -> Add a dll)

**Comment by srivatsn** [comment]
LGTM modulo the 3.5 testing. Please retarget this to the dev15.3.x branch once #2520 is merged in.

**Comment by tmeschter** [comment]
@davkean @srivatsn I encountered no problems with the 3.5 framework.

As best I can tell, `string` is the default type for resource items, and so the type information is never persisted to the file. That is, the item in the .resx file will simply always looks like this:

``` xml
<data name="MyString" xml:space="preserve">
  <value>Hello</value>
</data>
```

When adding a binary file to the .resx. you end up with something like this:

``` xml
<data name="MyAssembly" type="System.Resources.ResXFileRef, System.Windows.Forms">
  <value>D:\path\to\MyAssembly.dll;System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
</data>
```

The type of the MyAssembly item is `System.Resources.ResXFileRef`, rather than `byte[]`. The `System.Byte[], mscorlib, Version=...` bit is part of how a `ResXFileRef` is serialized to the .resx and never seems to be run through the multi-targeting service; hence it isn't a problem.

**Comment by srivatsn** [comment]
Can you fill out the template above and tag Matt for Preview4

**Comment by srivatsn** [comment]
Oh and retarget the PR to the dev15.3.x branch please

**Comment by tmeschter** [comment]
Tagging @MattGertz for approval. This change will be retargeted to the dev15.3.x branch once #2520 is merged in.

**Pull request merged**
