### PR TITLE
Stop walking dependency tree twice

### PR DESCRIPTION
**Pull request by davkean**
When called via IVsProject.IsDocumentInProject/ParseCanonicalName/IProjectTreeProvider.FindByPath, we walking the tree twice:

- Once with the path we were passed (ie C:\Project\Foo.cs")
- Once with the path we were passed, but relative to the project directory (Foo.cs, or ..\Analyzer.dll)

The later will never result in a match as we were comparing against "IProjectTree.FilePath" which is always a rooted path.

### CODE REVIEW

**Comment by abpiskunov** [comment]
Try searching in Solution Explorer and make sure graph nodes matching search are showing(same for scope), i remember this method do something there.

Thanks,
Anton

On Jul 4, 2017, at 8:01 PM, David Kean <notifications@github.com<mailto:notifications@github.com>> wrote:


@davkean<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavkean&data=02%7C01%7Canton.piskunov%40microsoft.com%7C64545d48676c4aa662cf08d4c35a7dae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636348240801114498&sdata=FVmtScl72PalHiYCBSpCBru6kIaxr7T6QHdgOutyJJg%3D&reserved=0> requested review from @dotnet/project-system on: dotnet/project-system#2562<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fproject-system%2Fpull%2F2562&data=02%7C01%7Canton.piskunov%40microsoft.com%7C64545d48676c4aa662cf08d4c35a7dae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636348240801114498&sdata=%2FpM3AiYSUfwAxZ7GK6iKIBQ8EgdyCDknQgqxZBzvrBM%3D&reserved=0> Stop walking dependency tree twice.

**Comment by davkean** [comment]
@abpiskunov Will do.

This basically halves the amount of time that is spent in FindByPathInternal (these are approximate scenarios):

Before:
image

After:
image

**Comment by davkean** [comment]
@abpiskunov As far as I see, this path is not hit when searching for the actual nodes. It is hit on other paths via the SolutionGraphManager but in those cases it's calling ParseCanonicalName with a full canonical name. Even if was hit in this path - I can't see how it worked, FilePath is returning a full path - relative paths will never match it.

**Comment by davkean** [comment]
But it looks like you very deliberately wrote this code, you've even got tests for it: GrouppedByTargetTreeViewProvider_WhenFindByPathAndRelativeNodePath_ShouldFind.

Looked through the history but it's been there since you wrong it originally.

**Comment by davkean** [comment]
After a little more debugging I should clarify; 

There are two types of nodes in play; project tree items and project tree.

Project tree items represent the actual individual analyzers, projects, packages, etc.
Project tree represent the Dependency, Analyzers, Projects nodes directly.

The former, we've not changed behavior - FilePath is always a combination of the ItemName rooted with the project. ie C:\Project\Foo.cs or C:\Project\Properties\Bar.cs.
The latter, however, we've changed bahavior, the FilePath for these are "Analyzers", "Projects", etc. This means if I search for "C:\Project\Analyzers" previously this would have matched, whereas now it doesn't.

I'm okay with the later change - it's questionable this should have matched in the first place. These really should get no FilePath, but the moniker returned from ParseCanonicalName should be in the identity syntax `>[identity]`, which I'm trying here: https://github.com/dotnet/project-system/issues/2559.

**Pull request merged**
