### PR TITLE
Run sign on official build.

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by davkean** [comment]
What's the back story on this?

**Comment by Pilchie** [comment]
I merged the equivalent fix in https://github.com/dotnet/project-system/pull/4197.

This was accidentally broken in https://github.com/dotnet/project-system/pull/4107.

**Comment by davkean** [comment]
Are we missing verification for this?

**Comment by Pilchie** [comment]
DevDiv insertions have validations, but we don't in our signed build leg.  I *think* there is now a signcheck task we could enable more locally, right @jmarolf ?

**Pull request closed without merging**
