### PR TITLE
Add missing public api to PublicAPI.Shipped.txt

### PR DESCRIPTION
**Pull request by ocallesp**
Code cleanup.

After I updated my local dotnet project system repo, and build it solution the file PublicAPI.Shipped.txt was modified to add some missing apis.

Perhaps this was part of a previous change.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8405)

### CODE REVIEW

**Comment by jacdavis** [comment]
I swear I saw these get added in Melissa's checkin from yesterday.

**Review by jacdavis — APPROVED** [review]
:shipit:

**Comment by melytc** [comment]
> I swear I saw these get added in Melissa's checkin from yesterday.

Yeah, they got added automatically in my PR https://github.com/dotnet/project-system/pull/8400. For future reference, should I remove them?

**Comment by MiYanni** [comment]
@melytc @ocalles There is a script in the build that moves the files from the Unshipped.txt to the Shipped.txt. So, if you ever seen an Unshipped.txt appear in your commit, just rebuild and it'll add those changes to the Shipped.txt.

**Pull request merged**
