### PR TITLE
Update VS validation and threading packages

### PR DESCRIPTION
**Pull request by drewnoakes**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6707)

### CODE REVIEW

**Review by davkean — APPROVED** [review]

**Review by jjmew — APPROVED** [review]
:shipit:

**Review by swesonga — APPROVED** [review]
:shipit:

**Review by dmonroym — APPROVED** [review]

**Review by tmeschter — APPROVED** [review]
Any particular reason? Or just keeping things up-to-date?

**Comment by drewnoakes** [comment]
> Any particular reason? Or just keeping things up-to-date?

I seem to remember work on threading analyzers lately. I was curious if we had any new diagnostics. Also this gets us off pre-release versions.

**Pull request merged**
