### PR TITLE
LOC CHECKIN | dotnet/project-system - master | 20171031

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by MattGertz** [comment]
Normal process, but they will almost certainly just be waved through.

**Comment by Pilchie** [comment]
Okay - @nguerrera can you fill out the ask mode template for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/473107?

**Comment by nguerrera** [comment]
@Pilchie Done.

**Comment by Pilchie** [comment]
Pre-approved to merge via [473107](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/473107)

**Pull request merged**
