### PR TITLE
A list of integration test scenarios to be automated

### PR DESCRIPTION
**Pull request by Pilchie**
What do people think?  What is missing?  What about the rough priorities?  What is covered by our current (disabled) integration tests?

### CODE REVIEW

**Comment by richaverma1** [comment]
@Pilchie, these are applicable to VB also I suppose? Will you also be looking through the scenario list that Matt is creating and updating this list?

**Comment by Pilchie** [comment]
@richaverma1 Yes and Yes.

**Comment by davkean** [comment]
We put repo docs under docs\repo.

**Comment by davkean** [comment]
I'm assuming these are in priority order? The top 4 are the ones I'd focus on and get them passing 100% before moving onto others.

**Comment by Pilchie** [comment]
Moved to `repo`.  Rough priority order, though feedback is welcome.  Agree that the first 4 should be solid before expanding scope.

**Comment by davkean** [comment]
👍

**Pull request merged**
