### PR TITLE
add xunit analyzers

### PR DESCRIPTION
**Pull request by jmarolf**
adding xunit analyzers and fixing up analyzer violations.  This is a test only change.

### CODE REVIEW

**Comment by srivatsn** [comment]
I think this is going to cause conflicts with @tmat 's Repotoolset PR since that includes the analyzer as well.

**Comment by tmat** [comment]
Yes, let's not do this at this point.

**Comment by jmarolf** [comment]
reverted in https://github.com/dotnet/project-system/pull/2620

**Comment by tmat** [comment]
@jmarolf Thanks. Let's revisit after I merge my PR

**Pull request merged**
