### PR TITLE
[WIP] FIX #189 - Set buildevent textinput font

### LINKED ISSUE #189: Change default font of build event text boxes to monospace
As mentioned in #176, it would be nice if the default font for the text boxes in the "Build events" page were monospace.

### PR DESCRIPTION
**Pull request by eriawan**
**Customer scenario**

Customer wants to be able to change the default font for the text boxes in the "Build events" property page were monospace.

**Bugs this fixes:** 

It is not actually a bug. It is adding enhancement on Build events property page to respect Text Editor setting of Visual Studio's Font and Color setting

**Workarounds, if any**

None. The property page needs to check the Fonts and Color setting.

**Risk**

Low. It only adds checking of Font and Color setting.

**Performance impact**

Very low performance impact, because it only checks Font and Color setting using `IVsFontAndColorStorage`

**Is this a regression from a previous update?**
No.

**Root cause analysis:**

Since this is an additional enhancement, there's no root cause.

**How was the bug found?**

Customer reported in issue #189

**Partner requested**

@davkean

### CODE REVIEW

**Comment by eriawan** [comment]
@davkean 

I have added method to check Font and Color setting in the constructor. 
Should I add the event handler for any changes in the Font and Color setting as well?

Although this PR only include the font check, I am confused on which event handler to use for changes in Font and Color setting, I have tried to use `IVsFontAndColorEvents` by making BuildEventsPropPage to implement `IVsFontAndColorEvents` but all of the implemented methods are not fired at all.
In case you want the event handler implemented, could you help me which interface I need to implement to handle Font and Color changes?

Thanks in advance 🙂

**Comment by davkean** [comment]
Looking around the tree, it looks like everyone listens to WM_SETTINGSCHANGE: see: ShellUtil.FontChangeMonitor for an example - it's reading the font from IUIService, instead you'll read it from IVsFontAndColorStorage.

I'd made this reusable similar to FontChangeMonitor so that we could consume this from other locations, such as the Debug command-line box.

**Comment by eriawan** [comment]
@davkean 

Ok, I'll try to use this `FontChangeMonitor`.

**Comment by shyamnamboodiripad** [comment]
@eriawan I am retargeting this PR to master since the dev15.6 branch is being deleted (master is the new branch for anything post-15.3).

cc @dotnet/project-system @srivatsn

**Comment by eriawan** [comment]
@shyamnamboodiripad thanks for the info! 🙂

**Comment by davkean** [comment]
@eriawan I've not seen an update for this - I'm going to close this for now. Feel free to pick this up again and submit a new PR that handles the font changes or reply to this and I'll reopen this one.

**Comment by eriawan** [comment]
@davkean 
Thanks for the reminder!
Actually I'm still working on this. 
Unfortunately I can't use the `FontChangeMonitor` that you suggested before.
As far as I know, FontChangeMonitor depends on changes on System font of Visual Studio, including the splash screen font but not capturing changes on Font and Color setting.

**Comment by eriawan** [comment]
@davkean 

I think I'll create a new PR. Could you tell me which branch to use as the base for my new PR? Is it `master`?

**Pull request closed without merging**
