### PR TITLE
Move props/targets into scripts

### PR DESCRIPTION
**Pull request by davkean**

### CODE REVIEW

**Comment by davkean** [comment]
Kinda regretting calling this "scripts", I'm thinking maybe splitting out the props/targets and the projects ."proj" Thoughts?

**Comment by drewnoakes** [comment]
Agree `proj` sounds better than `scripts`.

**Comment by tmeschter** [comment]
I see two distinct categories of files here: .props and .targets that are imported into other projects, and .proj files that are "standalone" projects in their own right. What if the former went into an `imports` directory, and the latter went into `proj`?

**Comment by davkean** [comment]
@tmeschter I went down that route and have merged that in https://github.com/dotnet/project-system/pull/5277.

**Pull request merged**
