### PR TITLE
Fix remaining localization issues in Advance Compilation page

### PR DESCRIPTION
**Pull request by Giftednewt**
This fixes the remaining localization issues in #52 by splitting the localized values for "report compile errors" and "Debug Info" from the underlying project property value.

### CODE REVIEW

**Comment by davkean** [comment]
@Giftednewt Thanks for the contribution. I'd prefer an approach that doesn't break the WinForms designer when we bring it up. The designer is not going to understand how to parse InitializeComponent due to the custom `new ComboItem(...)`. I'm fine with completely removing the population from within InitalizeComponent and instead populating the combo after `InitalizeComponent`.

The other thing to note, is that strings will still not be localized due the {Locked} in the common; that directs the localization tools not to localize the string.

**Comment by Giftednewt** [comment]
@davkean I'll get the population moved into the constructor after the call to InitializeComponent. I wasn't able to view the prop page in the designer within VS as for some reason it doesn't show as an option in the "open with..." list.

For the locked items is it just a case of removing the "{Locked}" comment from the common resource file?

I won't get chance to complete and commit the changes until mid next week, but when I'm back in civilization I'll get them actioned

**Comment by davkean** [comment]
No probs. Yes removing the {Locked} will be fine - I think you'll be better off pulling the strings out of the dlalog resx and just put them in the strong typed resources for the project.

The designer doesn't work in the tree right now with the new project system. We'll be bringing it up for Dev16 - but did not want to break it as it will increase the debt we have to pay off the next time we touch the page after your change.

**Comment by Giftednewt** [comment]
@davkean I tried moving the resources into the Designer.resx file but I get the following exception when trying to test in VS even if built from the command line

> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure ".Designer.resources" was correctly embedded or linked into assembly "Microsoft.VisualStudio.Editors" at compile time, or that all the satellite assemblies required are loadable and fully signed.

I'm assuming I've done something wrong when updating the file. Any pointers would be appreciated

**Comment by davkean** [comment]
You are likely running into: https://github.com/dotnet/project-system/issues/1058, revert any changes made to the ResourceManager property.

**Comment by Giftednewt** [comment]
@davkean reverting the changes to the ResourceManager property worked a treat. Are there any other changes that you would like me to make or are you happy with this now?

**Comment by davkean** [comment]
@Giftednewt Sorry missing this - will take a look tomorrow.

**Comment by Giftednewt** [comment]
@davkean did you get a chance to look at this?

**Comment by davkean** [comment]
Apologies for the really late reply. I'm sorry that I took so long to take another look at this. This goods great, and I've taken your changes, retargeted it to another branch, made a couple of minor changes (tabs and separate files for nested types) and merged it in: https://github.com/dotnet/project-system/commit/998b366b075bb16120952a94ec7c3242f4478367.

Thanks for the contribution!

**Pull request closed without merging**
