### PR TITLE
Updating our Roslyn dependencies to 2.3.0-beta3-61808-05

### PR DESCRIPTION
**Pull request by tannergooding**
Infrastructure only change to fix https://github.com/dotnet/project-system/issues/2315

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @dotnet/project-system

**Comment by tannergooding** [comment]
This actually needs another change, since we moved to a Roslyn version using System.Composition 1.0.31

**Comment by tannergooding** [comment]
This is currently block on getting a new Microsoft.VisualStudio.ProjectSystem.SDK package which no longer references `Microsoft.Composition`.

**Comment by tannergooding** [comment]
Logged https://devdiv.visualstudio.com/DevDiv/_workitems?id=448583 to track CPS getting a new NuGet package up.

**Comment by tannergooding** [comment]
Ok. Everything is building locally now.

Part of the version updates are just bringing existing references inline with what Roslyn is consuming (Roslyn does not list them as dependencies in its own NuGet packages).

The new package references are believed to be fallout from the few references we are still picking up from the VS build installed. We can probably remove them once those become NuGet packages.

**Comment by srivatsn** [comment]
You added some binlog files

**Comment by tannergooding** [comment]
Removed the binlog files.

**Comment by tannergooding** [comment]
Rebased onto current head so it runs on the updated images.

**Comment by tannergooding** [comment]
Infrastructure only change.

**Pull request merged**
