### PR TITLE
Add NullableReferenceTypes property

### PR DESCRIPTION
**Pull request by davkean**
Fixes adding configuration-specific property for #4058

Note: This is a configuraiton-specific property but writes itself without a configuration condition, similar to LangVersion. We need this because it's going to live on the Build property page which pulls from configuration.

You can access this using DTE.Configuration.Properties["NullableReferenceTypes"]. We do not yet have a strongly typed API for it and will do that when legacy adds support for it.

### CODE REVIEW

**Comment by davkean** [comment]
tag @jcouv

**Comment by davkean** [comment]
@jcouv here's an example of checking for CPS: https://github.com/dotnet/roslyn/blob/027d0f2535403ae8140d7669035956c2b1713c88/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs#L298. I have no idea how to this in a code fix.

**Comment by davkean** [comment]
Yes, though I think this will be one of the things that get "evaluation" handled.

**Comment by etbyrd** [comment]
I see in https://github.com/dotnet/roslyn/issues/22152 it is mentioned that we will need a UI change on the Build prop page. Do we have an idea of what that will look like?

**Comment by KenFoskeyInfo** [comment]
Just received this in VS 2019.

The "NullableReferenceTypes" parameter is not supported by the "Csc" task. Verify the parameter exists on the task, and it is a settable public instance property.

Is this related to the above?

**Comment by chucker** [comment]
@KenFoskeyInfo 

* is this in an SDK-style project?
* did you set `LangVersion` to `8.0`?

**Pull request merged**
