### PR TITLE
Reduce confusion between DisplayName & handshake between language service and project system

### PR DESCRIPTION
**Pull request by davkean**
Fixes: https://github.com/dotnet/project-system/issues/3327.

### CODE REVIEW

**Comment by Pilchie** [comment]
[This failure](https://ci.dot.net/job/dotnet_project-system/job/master/job/windows_debug_prtest/1140/) isn't something I've seen before.  @davkean @jmarolf @etbyrd have you?

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_debug please

**Comment by etbyrd** [comment]
I have never seen that failure before

**Comment by davkean** [comment]
I have see that failure, it's time based test so if it takes longer to run due to a slow machine than it will fail.

**Comment by davkean** [comment]
Heads up that until https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/126817?_a=overview is merged in, the first "config" in a multi-targeting project has the wrong name (just name, dimensions are correct), so instead of:

```
C:\Project\Project.csproj (Debug_AnyCPU_net45)
```

It will have the name:


```
C:\Project\Project.csproj (Debug_AnyCPU)
```

**Pull request merged**
