### PR TITLE
Add UI support for property "AuthenticationMode" to debug property page.

### PR DESCRIPTION
**Pull request by srdjanjovcic**

### CODE REVIEW

**Comment by srdjanjovcic** [comment]
@davkean @tmeschter -- Can you review those changes?

**Comment by davkean** [comment]
Are these new types deliberately public? Please don't add new public API here.

**Comment by srdjanjovcic** [comment]
Regarding public APIs. This is only way I found that you can actually implement user-serialized properties in property pages correctly.

If property page cannot access configuration state at top top of the view (which is shared among different property pages), it cannot implement user-serialized properties which understand selected configuration/platform.

**Comment by tmeschter** [comment]
@srdjanjovcic But why do they have to be public? Why won't `Friend` work?

**Comment by srdjanjovcic** [comment]
@tmeschter They are in different assembly.

**Comment by drewnoakes** [comment]
Can we use `InternalsVisibleTo` instead?

**Comment by srdjanjovcic** [comment]
@drewnoakes I do not know -- would it be acceptable? I am OK as long as team is OK with it.

I see that there are some InternalsVisibleTo used in project-system codebase (e.g., exposing Microsoft.VisualStudio.ProjectSystem.Managed.dll internals to Microsoft.VisualStudio.ProjectSystem.Managed.VS.dll)

Since those two are built in same code base, I guess that would be OK to do this?

**Comment by drewnoakes** [comment]
IVT isn't great, but it's better than adding public API. I'd vote for it here. Anyone object?

**Comment by srdjanjovcic** [comment]
I have updated PR to use InternalsVisibleTo

**Comment by srdjanjovcic** [comment]
@drewnoakes. @tmeschter, @davkean -- Any further feedback? Can we get this PR accepted?

**Pull request closed without merging**
