### PR TITLE
Move to latest analyzers package

### PR DESCRIPTION
**Pull request by mavasani**
I hope to start enabling rules and/or fixing violations in subsequent PRs. FYI @jinujoseph

### CODE REVIEW

**Comment by mavasani** [comment]
Ping..

**Comment by jinujoseph** [comment]
cc @Pilchie

**Comment by Pilchie** [comment]
Can you explain what happens with the `CA1063` violations in #2981 with this change?  Will we see them all the time, or are they suppressed somehow?

**Comment by mavasani** [comment]
What is the policy to merge in the repo? Do I need one more signoff from project-system team member?

**Comment by davkean** [comment]
What version of VS does this tie us to?

**Comment by mavasani** [comment]
If you are on the [latest preview build](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes) for VS2017.5 (or any internal build after it), you should be fine.

@jinujoseph I forget if we shipped IOperation APIs in Preview3 or Preview4 of VS2017.5? If it is the former, then analyzers should work fine on any build after Preview3.

**Comment by jinujoseph** [comment]
We shipped the ioperation API in Preview2

**Pull request merged**
