### PR TITLE
Remove unused rule properties

### PR DESCRIPTION
**Pull request by drewnoakes**

### CODE REVIEW

**Comment by davkean** [comment]
CPS fires a telemetry event for unused properties, is that what you used?

**Comment by drewnoakes** [comment]
> CPS fires a telemetry event for unused properties, is that what you used?

I didn't know that. These rules are used by the up to date check, and none of the code in the up to date check uses these properties, hence I concluded they were redundant.

When is the event fired? I'll try and see whether these appear.

**Comment by davidwengier** [comment]
> When is the event fired?

It's a telemetry event called `VS/ProjectSystem/Cps/Rule/PropertiesUnused`.

**Comment by drewnoakes** [comment]
> It's a telemetry event called `VS/ProjectSystem/Cps/Rule/PropertiesUnused`.

I didn't see that event fire, however I did see `vs/projectsystem/cps/rulepropertiesusage` on solution close. It has a few interesting properties:

- `vs.projectsystem.cps.rule/propertiesunused`
- `vs.projectsystem.cps.rule/propertiesused`
- `vs.projectsystem.cps.rulename`

Creating a new .NET Core console app, building it a few times then closing the solution gives the following unused properties:

| Rule | Unused |
|-----|-------|
| Compile | {ItemType} AutoGen CustomTool CustomToolNamespace DesignTime DesignTimeSharedInput FullPath Generator LastGenOutput |
| CopyUpToDateMarker | Visible |
| ResolvedFrameworkReference | TargetingPackPath Profile PrivateAssets |
| UpToDateCheckBuilt | Visible |
| ResolvedAssemblyReference | Aliases CopyLocal Description EmbedInteropTypes FileType FrameworkFile HintPath Identity IsWinMDFile Name ReferenceFromSDK RequiredTargetFramework ResolvedFrom ResolvedPath RuntimeVersion SDKIdentity SpecificVersion StrongName Version WinMDFile  |
| UpToDateCheckInput | Visible |
| ResolvedPackageReference | Dependencies Description ExcludeAssets FrameworkName FrameworkVersion IncludeAssets IsTopLevelDependency NoWarn OriginalItemSpec Path PrivateAssets RuntimeIdentifier TargetFramework Version Visible |
| FrameworkReference | PrivateAssets |

`UpToDateCheckOutput` is missing from this list, but is changed in this PR.

`CopyUpToDateMarker`'s `Visible` property should also be removed in this PR.

The large number of properties in `Resolved*` are due to those rules being used as browse objects (#5076).

**Comment by davidwengier** [comment]
Whoops, got my event names and property names mixed up. Thats the right event :)

**Comment by drewnoakes** [comment]
I pushed changes to `CopyUpToDateMarker` as well.

@davkean it seems the build's borked on this PR too.

**Pull request merged**
