### PR TITLE
Fix 'sequence has no elements' exception

### PR DESCRIPTION
**Pull request by drewnoakes**
While testing this in Dev17, this code was throwing an exception as the predicate did not find a match.

This change makes the code tolerant of this situation.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/7275)

### CODE REVIEW

**Review by swesonga — APPROVED** [review]

**Comment by tmeschter** [comment]
I wonder when this can happen. Perhaps if we open the property pages right after the solution has opened, and the workspace hasn't populated yet?

**Review by tmeschter — APPROVED** [review]

**Review by MiYanni — APPROVED** [review]
Code looks good but I gotta wonder what changed to make this situation happen.

**Comment by drewnoakes** [comment]
> I wonder when this can happen. Perhaps if we open the property pages right after the solution has opened, and the workspace hasn't populated yet?

Seems likely, though why now and why so repeatedly on my machine? Thinking about this again the next day, I'm not sure this is the best fix. Will think about this some more before.

**Comment by drewnoakes** [comment]
@davkean do you have some insight here?

This is the dynamic enum provider for the startup object, and it seems we can hit it when no project is found in the workspace.

Ideally we would wait for things to catch up, but it's not clear to me how that would work.

This PR at least stops there being an exception. But it will result in the "startup object" drop-down being empty.

**Comment by davkean** [comment]
This code needs to wait for the language service to be initialized. It also needs to use the Roslyn project specific to the configuration that that it belongs to, currently its just picking the first. Can IDynamicEnumValuesProvider's be specific to configurations?

**Comment by drewnoakes** [comment]
> This code needs to wait for the language service to be initialized

@davkean any tips on how to do this? Would `IActiveWorkspaceProjectContextHost.PublishAsync` achieve this?

> Can IDynamicEnumValuesProvider's be specific to configurations?

Yes. `LaunchTargetPropertyPageEnumProvider` is. However we don't support differing startup objects by configuration today. We can, of course, change that.

**Comment by drewnoakes** [comment]
Never mind. I worked it out.

**Pull request closed without merging**
