### PR TITLE
Enable NuGet package signing

### PR DESCRIPTION
**Pull request by tmat**
**Customer scenario**

Infrastructure only change. NuGet packages are required to be signed.

**Bugs this fixes:** 

**Workarounds, if any**

**Risk**

**Performance impact**

**Is this a regression from a previous update?**

**Root cause analysis:**

**How was the bug found?**

(E.g. customer reported it vs. ad hoc testing)

### CODE REVIEW

**Comment by Pilchie** [comment]
Approved - but keep in mind that if we don't take any more escrow changes for 15.7, then this change won't apply to packages that match the last inserted build.

**Comment by tmat** [comment]
@Pilchie All packages published to NuGet after 5/15 will have to be signed. If we publish unsigned 15.7 packages before that we should be fine.

**Comment by tmat** [comment]
Test failure due to networking issue.

**Comment by tmat** [comment]
test windows_release please

**Comment by tmat** [comment]
test windows_debug  please

**Comment by jasonmalinowski** [comment]
> Approved - but keep in mind that if we don't take any more escrow changes for 15.7, then this change won't apply to packages that match the last inserted build.

@Pilchie and @tmat, to this point: what would you like to do? We're seeing insertions triggered today because of this.

**Comment by Pilchie** [comment]
I expect will have an escrow insertion to do for https://github.com/dotnet/project-system/pull/3436 soon, so it will probably work itself out.

**Pull request merged**
