### PR TITLE
Pass through RootNamespace to language-service

### PR DESCRIPTION
**Pull request by davkean**
Introduce a new rule; LanguageService.xaml that lets us pass through properties to the language-service, such as RootNamespace, without needing to write any additional code - similar to NuGutRestore.xaml.

### CODE REVIEW

**Comment by genlu** [comment]
I'm trying to test this locally, but it seems the new code in `ProjectPropertiesItemHandler` isn't called though.

**Comment by davkean** [comment]
RootNamespace comes from both. This is untested yet, I'll look this morning.

**Comment by genlu** [comment]
@davkean Any update on this?

**Comment by davkean** [comment]
I had a bug where the format string I was passing the logger was wrong, after I fixed this - this worked for me.

**Comment by genlu** [comment]
I tried to build and deploy from latest source again, still couldn't get this to work. Same behavior as I mentioned before, when opening a solution, "roonamespace" property is part of the project change of `ConfigurationGeneral` evaluation rule, not `LanguageService`. Did I miss anything?

**Comment by davkean** [comment]
RootNamespace will be a part of both rules.

You need launch using Launch.cmd or F5 from our solution for the new rules to take effect. If you don't do this, the new rule will not be picked up.

**Pull request merged**
