### PR TITLE
Hide the Hot Reload check box when Remote Debugging is checked

### PR DESCRIPTION
**Pull request by drewnoakes**
Follows #7497 where this same check is made in the project launch target provider.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/7498)

### CODE REVIEW

**Comment by tmeschter** [comment]
I think a better approach would be to conditionally disable the Hot Reload control rather than hide it, if we had that ability. That at least hints to the user that Hot Reload is _in general_ available but disabled for some other reason.

**Comment by MiYanni** [comment]
@tmeschter Do we have that as a design concept for the new property pages (situationally disabled controls)? Maybe an alternative design is to show some text about Hot Reload when it cannot be used (different XAML element with opposite conditions), and then disable that text and enable the control when it can be used.

**Comment by drewnoakes** [comment]
We have no support for disabling controls currently. Let's discuss this at our next meeting.

If we had and used that here, we would also need to uncheck hot reload when remote debugging was checked.

My vote is to merge this as is for now. It's consistent with how we handle other such features.

**Review by tmeschter — APPROVED** [review]

**Comment by tmeschter** [comment]
Yeah, I don't want to hold this up--it just points to a general issue that we should tackle at some point.

**Review by MiYanni — APPROVED** [review]

**Pull request merged**
