### PR TITLE
Consolidate reference manager capabilities

### LINKED ISSUE #5829: Consolidate reference manager capabilities
Currently we have capabilities such as:

- `ReferenceManagerAssemblies`
- `ReferenceManagerBrowse`
- `ReferenceManagerCOM`
- `ReferenceManagerProjects`
- `ReferenceManagerSharedProjects`
- `ReferenceManagerWinRT`

Additionally we have capabilities such as:

- `AssemblyReferences`
- `COMReferences`
- `PackageReferences`
- `ProjectReferences`
- `SharedProjectReferences`
- `WinRTReferences`

It may be possible to consolidate these.

Note that `ReferenceManagerBrowse` has no analogue, nor does `PackageReferences`.

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #5829.

We have existing capabilities for each type of reference. This change removes the Reference Manager specific ones, using the reference type capabilities instead.

It also removes implementations of `IVsReferenceManagerUserAsync`, as  those provided by CPS are equivalent.

This change removes a condition that would hide the COM references tab when targeting .NET Core App versions before 3.0.

### CODE REVIEW

**Comment by davkean** [comment]
I think we can take a step further and just delete all of our IVsReferenceManagerUserAsync implementators - they all appear to do nothing over the built-in ones except check capability in IsApplicable instead of at the Export level. I can't see why they were added in the first place? Maybe so we could use different capabilities to drive it?

**Comment by drewnoakes** [comment]
Force-pushed a commit that removes most of this code instead. The implementations provided by CPS are adequate given we don't need these `ReferenceManager*` capabilities.

**Comment by davidwengier** [comment]
> This change removes a condition that would hide the COM references tab when targeting .NET Core App versions before 3.0.

This seems bad. So if I target .NET Standard I'll now be able to add a reference to a COM library even though it might not/won't work?

**Comment by davkean** [comment]
Oh I missed that - that wasn't in the original change. What impact did removing COMReferences capability have?

**Comment by drewnoakes** [comment]
COM reference issue addressed in #5962.

**Pull request merged**
