### PR TITLE
Add spanish test run

### PR DESCRIPTION
**Pull request by jmarolf**
fixes https://github.com/dotnet/project-system/issues/3441

### CODE REVIEW

**Comment by jmarolf** [comment]
test ci please

**Comment by jmarolf** [comment]
test ci please

**Comment by jmarolf** [comment]
Just ran this on [Jenkins](https://ci.dot.net/job/dotnet_project-system/job/master/job/GenPRTest/job/windows_spanish_debug/1/console)

There is not Visual Studio installation on the Jenkins image:
```ini
11:53:55 Started by user Jonathon Marolf
11:53:55 Notifying endpoint with credentials id 'helix-int-notification-url'
11:53:55 Notifying endpoint with credentials id 'helix-prod-notification-url'
11:53:55 Building remotely on Windows.10.Amd64.ClientRS3.ES.Open-0405115346104-0 (rs3esopen00003Q) (Windows.10.Amd64.ClientRS3.ES.Open) in workspace D:\j\workspace\windows_spani---f6bbc085
11:53:55 [WS-CLEANUP] Deleting project workspace...
11:53:55 Selected Git installation does not exist. Using Default
11:53:57 Cloning the remote Git repository
11:53:57 Cloning repository https://github.com/dotnet/project-system.git
11:53:57  > git init D:\j\workspace\windows_spani---f6bbc085 # timeout=10
11:53:57 Fetching upstream changes from https://github.com/dotnet/project-system.git
11:53:57  > git --version # timeout=10
11:53:58  > git fetch --tags --progress https://github.com/dotnet/project-system.git +refs/heads/*:refs/remotes/origin/* # timeout=90
11:54:02  > git config remote.origin.url https://github.com/dotnet/project-system.git # timeout=10
11:54:02  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
11:54:03  > git config remote.origin.url https://github.com/dotnet/project-system.git # timeout=10
11:54:03 Fetching upstream changes from https://github.com/dotnet/project-system.git
11:54:03  > git fetch --tags --progress https://github.com/dotnet/project-system.git +refs/heads/*:refs/remotes/origin/* # timeout=90
11:54:04  > git rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
11:54:04  > git rev-parse "refs/remotes/origin/refs/heads/master^{commit}" # timeout=10
11:54:04 Checking out Revision 0104992d525dc706eba1f8793a2edab9ad9b9a7d (refs/remotes/origin/master)
11:54:06 Commit message: "Merge pull request #3448 from dotnet/merges/dev15.7.x-to-master"
11:54:06  > git config core.sparsecheckout # timeout=10
11:54:07  > git checkout -f 0104992d525dc706eba1f8793a2edab9ad9b9a7d
11:54:08 First time build. Skipping changelog.
11:54:08 Run condition [Current build status] enabling prebuild for step [[Archive the artifacts]]
11:54:08 [windows_spani---f6bbc085] $ cmd /c call C:\Users\runner\AppData\Local\Temp\jenkins72732001424436652.bat
11:54:09 
11:54:09 D:\j\workspace\windows_spani---f6bbc085>.\build\CIBuild.cmd -configuration debug -prepareMachine 
11:54:10 Downloading vswhere
11:54:12 No se puede enlazar el argumento al par metro 'Path' porque es nulo.
11:54:12 System.Management.Automation.ParameterBindingValidationException: No se puede enlazar el argumento al par metro 'Path' porque es nulo.
11:54:12    en System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
11:54:12    en System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
11:54:12    en System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
11:54:12    en System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
11:54:12 en LocateVisualStudio, D:\j\workspace\windows_spani---f6bbc085\build\Build.ps1: l¡nea 93
11:54:12 en <ScriptBlock>, D:\j\workspace\windows_spani---f6bbc085\build\Build.ps1: l¡nea 164
11:54:12 en <ScriptBlock>, <sin archivo>: l¡nea 1
11:54:12 Killing running build processes...
11:54:12 
```

**Comment by davkean** [comment]
Do we have VS on those machines now?

**Comment by davkean** [comment]
Haven't seen movement on this for a month, closing it out.

**Pull request closed without merging**
