### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by smitpatel**
They were old, we never ran some of them so seemed low value. Thoughts?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9111)

### CODE REVIEW

**Review by drewnoakes — APPROVED** [review]
Maybe get rid of the table altogether, if it's only going to have one row.

**Comment by smitpatel** [comment]
I will update to single line tomorrow.

**Comment by drewnoakes** [comment]
@MiYanni do you have an opinion on this?

**Comment by smitpatel** [comment]
The table shows different stages of pipeline working or not. I couldn't think of an easy way to represent that data so keeping it table only.

**Comment by MiYanni** [comment]
@smitpatel If you are removing the table, you need to also remove the references to all the elements on the table. The references are at the very bottom of the document.

**Pull request merged**
