### PR TITLE
Bumping up version for 16.0

### PR DESCRIPTION
**Pull request by Shyam-Gupta**
Temporarily updating version to 2.11.0 for 16.0 so that insertion builds do not fail.
We might need to change it to 3.0.0

### CODE REVIEW

**Comment by davkean** [comment]
Can you make this commit on top of these commits: https://github.com/dotnet/project-system/pull/3692 to front load the conflict when it gets merged into master?

**Comment by Shyam-Gupta** [comment]
This change is in master for Dev16. Whereas the other change is in dev15.9.x. So there wont be any merge conflicts.

**Comment by davkean** [comment]
Tonight when 15.9 merges into master there will be a conflict that I'll immediately need to fix.

**Comment by davkean** [comment]
ie there one: https://github.com/dotnet/project-system/pull/3694#event-1724425019.

**Pull request merged**
