### PR TITLE
Bump package versions

### PR DESCRIPTION
**Pull request by drewnoakes**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8346)

### CODE REVIEW

**Review by melytc — APPROVED** [review]
Out of curiosity, do you bump these versions running a command or manually?

**Review by MiYanni — APPROVED** [review]

**Comment by drewnoakes** [comment]
> Out of curiosity, do you bump these versions running a command or manually?

Manually. Usually I start with one package, then do a restore. The restore usually fails, saying there are version conflicts. Then I go through and update the other packages to address those conflicts.

**Comment by drewnoakes** [comment]
I kicked off another build to get the markdown check green, which did actually make it green. It made everything else red though :)

> System.IO.FileLoadException : Could not load file or assembly 'System.Composition.TypedParts, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by MiYanni** [comment]
> I kicked off another build to get the markdown check green, which did actually make it green. It made everything else red though :)

You don't need to re-run the pipelines for the markdown check since the markdown check is just a GitHub action (no relation to AzDO/the pipelines). Just click on the Details link and then hit 're-run job'. I've told the pipelines to re-run in AzDO.

**Review by tmeschter — APPROVED** [review]

**Comment by MiYanni** [comment]
@drewnoakes Looks like the build failure is a legitimate one for changing these package versions. I'd clear your NuGet cache locally and try to build there to see if it works.

**Comment by ocallesp** [comment]
The unit test GetFileAsync_WhenAppDesigner_ReturnsPathUnderAppDesigner is failing

**Comment by drewnoakes** [comment]
315 tests are failing with:

> System.IO.FileLoadException : Could not load file or assembly 'System.Composition.AttributedModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

My hunch is that a package is not defining its dependencies correctly.

There's nothing urgent in this PR. I'll revisit after completing other higher-priority work.

**Pull request closed without merging**
