### PR TITLE
Add analyzer to enforce use of `is null` for null checks

### PR DESCRIPTION
**Pull request by drewnoakes**
Seems like we prefer `is null` over `== null` during PR reviews.

Here's an analyzer that does that for us.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8345)

### CODE REVIEW

**Review by MiYanni — APPROVED** [review]
I think it is a good change and gets people in the habit of using the pattern matching notation.

**Review by melytc — APPROVED** [review]
My understanding is that if we don't expect to have an operator overload for `==`, then using the `is` operator should be fine. I also don't have a strong preference, but this looks nice. 🙂

**Comment by tmeschter** [comment]
Of course, it's always possible for an `==` operator to be added later, potentially changing the meaning of our code without us realizing. I prefer the `is null` approach myself, so I'm all for this. :-D

**Review by tmeschter — APPROVED** [review]

**Comment by drewnoakes** [comment]
Let's hold off on merging this until p2, in case we want to revert anything prior to that.

**Pull request merged**
