### PR TITLE
Fix XAML rule setup for up to date check

### PR DESCRIPTION
**Pull request by panopticoncentral**
Customer scenario

The customer makes a change to their .NET Core project and runs. The project system thinks the project is up to date and doesn't rebuild, so the customer doesn't see their changes.

Bugs this fixes:

#3050

Workarounds, if any

Customer has to do a rebuild.

Risk

Low, this is installing a file that is missing.

Performance impact

None, makes things work the way they're supposed to.

Is this a regression from a previous update?

Yes.

Root cause analysis:

A fix for up to date checks introduced a new XAML file which needed to be added to setup to function in setup scenarios. This didn't show up in F5 testing of the project system.

How was the bug found?

Customer report

### CODE REVIEW

**Comment by jmarolf** [comment]
@panopticoncentral can you create a bug so we add infrastructure to verify the swr files are up-to-date with the xaml files?

**Comment by natidea** [comment]
Approved to merge via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/559198

**Comment by Pilchie** [comment]
I happened to be online, so I merged this so that we could get a signed build going for insertion a bit earlier.

**Comment by panopticoncentral** [comment]
Thanks, I was just checking in.

**Pull request merged**
