### PR TITLE
Added tests for TempPEBuildManager

### PR DESCRIPTION
**Pull request by davidwengier**
Part of #4163

Tests for the TempPEBuildManager

### CODE REVIEW

**Comment by davidwengier** [comment]
@jmarolf Do we have any way of getting the HTML file that the build mentions in the failure? It looks like all of the tests actually passed, and indeed they do on my machine too.

**Comment by jmarolf** [comment]
@davidwengier under `Debug Test Result Logs` you can get the raw files

1. Look in the artifacts folder:
image

2. Download the files: 
image

**Comment by jmarolf** [comment]
This appears to be the exception

```console
Microsoft.VisualStudio.Diagnostics.ThrowingTraceListener+DebugAssertFailureException: Instance of CancellationSeries not disposed before being finalized
Stack at construction:
   en Microsoft.VisualStudio.Threading.Tasks.CancellationSeries..ctor(CancellationToken token)
   en Microsoft.VisualStudio.Threading.Tasks.TaskDelayScheduler..ctor(TimeSpan taskDelayTime, IProjectThreadingService threadService, CancellationToken originalSourceToken)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.TestTempPEBuildManager.CreateTaskScheduler()
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPE.TempPEBuildManager.<ApplyAsync>d__17.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPE.TempPEBuildManager.ApplyAsync(DesignTimeInputsDelta value)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.TestTempPEBuildManager.<>n__1(DesignTimeInputsDelta value)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.TestTempPEBuildManager.<SetInputs>d__17.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.TestTempPEBuildManager.SetInputs(String[] designTimeInputs, String[] sharedDesignTimeInputs)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.<Process_BothDesignTimeInputsToSharedOnly_WatchesOneFile>d__7.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Microsoft.VisualStudio.ProjectSystem.VS.TempPEBuildManagerTests.Process_BothDesignTimeInputsToSharedOnly_WatchesOneFile()
   en System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   en System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   en System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   en Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
   en Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__1()
   en Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
   en Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<InvokeTestMethodAsync>b__0()
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
   en Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__48.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
   en Xunit.Sdk.XunitTestInvoker.InvokeTestMethodAsync(Object testClassInstance)
   en Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestInvoker`1.<RunAsync>b__47_0()
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   en Xunit.Sdk.TestInvoker`1.RunAsync()
   en Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator)
   en Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
   en Xunit.Sdk.TestRunner`1.<>c__DisplayClass43_0.<RunAsync>b__0()
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
   en Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestRunner`1.RunAsync()
   en Xunit.Sdk.XunitTestCaseRunner.RunTestAsync()
   en Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestCaseRunner`1.RunAsync()
   en Xunit.Sdk.XunitTestCase.RunAsync(IMessageSink diagnosticMessageSink, IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
   en Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)
   en Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
   en Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Xunit.Sdk.TestMethodRunner`1.RunAsync()
   en Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments)
   en Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestInvoker`1.<<RunAsync>b__47_0>d.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(Object state)
   en System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(Task task, Boolean canInlineContinuationTask)
   en System.Threading.Tasks.Task.FinishContinuations()
   en System.Threading.Tasks.Task.FinishStageThree()
   en System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   en Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__48.MoveNext()
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   en System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
   en Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _)
   en Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
   en Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass11_0.<WorkerThreadProc>b__0(Object _)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en Xunit.Sdk.ExecutionContextHelper.Run(Object context, Action`1 action)
   en Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
   en Xunit.Sdk.XunitWorkerThread.<>c.<.ctor>b__1_0(Object s)
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart(Object obj)

   en Microsoft.VisualStudio.Diagnostics.ThrowingTraceListener.Fail(String message, String detailMessage) en F:\workspace\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed.TestServices\Diagnostics\ThrowingTraceListener.cs:l¡nea 25
   en System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   en System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessageFormat, Object[] args)
   en Microsoft.VisualStudio.Threading.Tasks.CancellationSeries.Finalize() en F:\workspace\_work\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed\Threading\Tasks\CancellationSeries.cs:l¡nea 42

```

**Comment by davidwengier** [comment]
Thanks Jon, will check it out

**Pull request merged**
