### PR TITLE
Remove ProjectNotRunnableDirectlyException

### PR DESCRIPTION
**Pull request by MiYanni**
Fixes: [AB#1245470](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1245470)
Related: https://github.com/dotnet/project-system/pull/6443#pullrequestreview-458792319

Currently, `ProjectNotRunnableDirectlyException` is thrown when the project cannot be debugged, such as a class library. Then, this exception is explicitly caught in `CanBeStartupProjectAsync`. If caught, it cannot be a startup projects (returns false). Otherwise, the method returns true.

This exception is thrown in `GetTargetCommandAsync`. Working up the call stack, this is used in the 2 public methods, `QueryDebugTargetsForDebugLaunchAsync` and `QueryDebugTargetsAsync`. These implement a couple of provider interfaces for the `ProjectLaunchTargetsProvider`. So, anything that calls these methods has the potential of throwing a `ProjectNotRunnableDirectlyException`.

In the attached issue, the exception the user saw was correctly being thrown from `CanBeStartupProjectAsync` according to the provided call stack. However, it is not a good practice to use exceptions as the 'happy path' for logic, even if they are being caught and handled. Instead, I've used a sentinel value `null` to represent the 'bad path' for this call stack. It isn't the best design, but it is the simplest solution without redesign of the calling structure. In the PR, the changes mainly relate to passing `null` up the call stack until it reaches `CanBeStartupProjectAsync`. If `null` is given to that method, it returns false. Otherwise, it returns true. If `null` reaches the 2 public methods, they will return an empty array to adhere to the interface the methods implement.

Other changes in this PR are addressing @drewnoakes comments on the [PR that added this exception](https://github.com/dotnet/project-system/pull/6443#pullrequestreview-458792319). Plus, minor cleanup in files that I touched, such as tab alignment and extra whitespace being removed.

### CODE REVIEW

**Comment by davkean** [comment]
Please test these two scenarios:

## Class Library
1. File -> New -> Class Library (.NET COre)
2. F5

Expected: Get this _exact_ error:

---------------------------
Microsoft Visual Studio
---------------------------
A project with an Output Type of Class Library cannot be started directly.


In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.
---------------------------
OK   
---------------------------


## Unit Test inherits launchsettings.json

1. File -> New -> Unit Test Project
2. Properties -> Debug -> Check "Enable native code debugging"
3. Save
4. Set a breakpoint in test so that it will stop
5. Right-click on same test and choose Debug

Expected: Native debugging is enabled (have a look at CallStack to see if you see native dlls on it it)

**Review by tmeschter — APPROVED** [review]
Approved, pending review of the test cases suggested by @davkean.

**Review by swesonga — APPROVED** [review]

**Comment by MiYanni** [comment]
@davkean For Scenario 1:
Updated the 2 public methods to `throw new Exception(VSResources.ProjectNotRunnableDirectly);` when it is null. Now, it properly displays the dialog with the message:
image

For Scenario 2:
When debugging, I had to "Show External Code" in the Call Stack window. After that, I could see these 2 unmanaged DLLs.
image

**Comment by davkean** [comment]
👍

**Pull request merged**
