### PR TITLE
Fix for NFE on Package properties (Readme/Icon)

### PR DESCRIPTION
**Pull request by MiYanni**
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748809

## Summary
In certain situations, the user can provide values to the Package Readme and Package Icon properties that are MSBuild evaluated to be empty (such as an MSBuild property that doesn't exist). CPS doesn't allow the `Include` attribute of a None item to be empty. This will throw an NFE in this scenario. This wraps our logic that attempts to do this in a try/catch so that we simply don't take action if the operation throws. We'll return the current value so it doesn't affect the user negatively.

Testing this, there is one side-effect. If it evaluates the value as empty, it still creates the property. This seems to be how `AddAsync` is implemented on the `IProjectItemProvider`. If this isn't acceptable, I think a change on the CPS side would ne necessary. Otherwise, the changes here provide the desired goal of not causing an NFE and keeps the user from inputting invalid information.

## Additional Details
There was some deeper discussion about this situation. For example, there isn't a way for a user to enter an unevaluated MSBuild property value as the `Include` attribute (for the None item) via the property pages. It will always try to evaluate it. These properties are special because they create this None item as it is necessary for the Pack operation. There's likely some QoL that could be done around these scenarios but this isn't the PR to do those changes.

## Before GIF
BrokenPackageProperty

## After GIF
FixForPackageProperty

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9002)

### CODE REVIEW

**Comment by drewnoakes** [comment]
In the second GIF, are you entering `$(UndefinedProperty)`, and seeing that value disappear when tabbing out? That seems like a suboptimal experience.

**Comment by drewnoakes** [comment]
Can we apply the change to the code that tries to add the project item, so that it doesn't do that when the value is empty?

**Comment by MiYanni** [comment]
@drewnoakes 
> In the second GIF, are you entering $(UndefinedProperty), and seeing that value disappear when tabbing out? That seems like a suboptimal experience.

The experience is that when an invalid item is entered, no changes are made to the property so the current value is retained. It seems like the best outcome given the situation because they're legally not allowed to enter that value. Some other properties on the property pages act this way currently.

> Can we apply the change to the code that tries to add the project item, so that it doesn't do that when the value is empty?

We don't know the value is empty. The user provides something like you said, `$(UndefinedProperty)`, and that's what we see. When we hand that to CPS, they evaluate it. We never see that evaluated value on our side; it will be set to the `Include` metadata for the None item. Keep in mind that the value of the property itself and the value of `Include` in the None item can be 2 different values entirely. The property value indicates its relative path in the package during the Pack operation and the `Include` path for the None item is the path on-disk within the project. The user needs to provide the path on-disk and we set the property value appropriately.

**Comment by drewnoakes** [comment]
Understood.

My only suggestions here would be to investigate:

1. Can we reduce the scope of the try/catch to just the operation we know will fail? For example the `AddAsync` call.
2. Can we catch a specific exception type? Catching all exceptions is a bad idea as it can hide all kinds of problems. Would `ArgumentException` suffice here?

**Comment by MiYanni** [comment]
@drewnoakes 
> Can we reduce the scope of the try/catch to just the operation we know will fail? For example the AddAsync call.
Both `SetUnevaluatedIncludeAsync` on IProjectItem and `AddAsync` on IProjectItemProvider do the same `Requires.NotNullOrEmpty` check. So, that's why I wrapped the entire if-else statement. However, I can just wrap each of these individually.

#### On AddAsync
image

#### On SetUnevaluatedIncludeAsync
image

> Can we catch a specific exception type? Catching all exceptions is a bad idea as it can hide all kinds of problems. Would ArgumentException suffice here?
After double checking these, `ArgumentException` would be best. Good idea. 👍

**Review by drewnoakes — APPROVED** [review]
Looks good!

**Pull request merged**
