### PR TITLE
LOC CHECKIN | project-system - master | 20180112

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by Pilchie** [comment]
@tmeschter - can you retarget this to `dev15.6.x` and rebase if necessary?

**Comment by tmeschter** [comment]
@Pilchie Is `dev15.6.x` flowing into `master` automatically?

**Comment by Pilchie** [comment]
Yes, @dotnet/roslyn-infrastructure is supposed to handle that, barring any conflicts that need intervention.

**Comment by tmeschter** [comment]
@Pilchie Rebased.

**Comment by jasonmalinowski** [comment]
@tmeschter Should we be having them localize the dev15.6.x branch directly at this point rather than us retargeting? Otherwise there's a few day lag, and in some cases 15.6-specific strings (if those exist) will never appear in master.

**Comment by tmeschter** [comment]
@jasonmalinowski Possibly, depending on how long we expect active development to be going on in dev15.6.x. We should discuss offline.

**Pull request merged**
