### PR TITLE
Don't drain critial tasks when doing up to date check

### LINKED ISSUE #2385: Determine relationship with up to date check and draining critical tasks
Rationalize whether we need to be run before or after draining critical tasks (BeforeDrainCriticalTasks metadata) - what if we haven't restored yet and NuGet brings down a bunch of packages, should we build or not?

### PR DESCRIPTION
**Pull request by panopticoncentral**
**Customer scenario**

A user tries to build while a NuGet restore (or some other critical build task) is running in the background. The up to date check currently will block on the UI thread, waiting for the background critical task to complete before returning whether the project is up to date. Since most critical tasks will cause the up to date check to fail, we should instead *not* wait for critical tasks to complete (meaning no UI delays) and just fail the up to date check if such tasks are running.

**Bugs this fixes:** 

Fixes #2385 

**Workarounds, if any**

Go get a cup of coffee.

**Risk**

Low, the major risk would be that we would fail the up to date check when we shouldn't, which would just mean MSBuild will be called when it could be skipped.

**Performance impact**

Improves performance because it removes a UI delay.

**Is this a regression from a previous update?**

No.

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz for approval.

**Comment by MattGertz** [comment]
Nice. :-)

**Comment by natidea** [comment]
Approved to merge for Preview 4

**Comment by panopticoncentral** [comment]
@srivatsn I realized you didn't tag this with a milestone, I assume preview 4 is OK?

**Comment by srivatsn** [comment]
Yes. master is Preview4.

**Pull request merged**
