### PR TITLE
Support attached transitive package and project nodes

### PR DESCRIPTION
**Pull request by drewnoakes**
This PR extends the assets file snapshot to include data about packages and projects (collectively referred to as libraries). The snapshot is now split by target to make lookup more efficient.

Assets file snapshot types have been moved into their own "Models" namespace.

Packages have sub-nodes for displaying assembly groups (compile time assemblies, framework assemblies).

image

image

image

image

### CODE REVIEW

**Comment by davkean** [comment]
I don't understand the "Compile Time Assemblies" under the project, is that the result of the project?

**Comment by davkean** [comment]
It would be nice to have the "full path" in the browse object for all objects.

**Comment by drewnoakes** [comment]
> I don't understand the "Compile Time Assemblies" under the project, is that the result of the project?

Yeah, it's just the output DLL. Not sure it makes sense either. I've removed it.

> It would be nice to have the "full path" in the browse object for all objects.

Done.

---

image

image

**Comment by drewnoakes** [comment]
Fixed this for assemblies in packages too:

image

**Comment by drewnoakes** [comment]
This is basically #5740.

**Pull request merged**
