### PR TITLE
Address Properties being null in some cases

### PR DESCRIPTION
**Pull request by adamint**
Add note to docs mentioning that you cannot expect properties to be non-null.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8681)

### CODE REVIEW

**Comment by drewnoakes** [comment]
Do we understand why this occurs in different locales? Given we on the engineering team mostly test in English, this sense likely to come up again and again. If we could prevent it, that would be best.

**Comment by adamint** [comment]
No, we don't understand why this occurs, and we will need to do an investigation on this in the future

**Comment by drewnoakes** [comment]
I think we should try and identify why this occurs. Is it that the localised string is not present?

**Comment by smitpatel** [comment]
@drewnoakes - Should we close this? In future when we come across the same error, we can investigate and make a note in doc with details why it occurs.

**Comment by drewnoakes** [comment]
Yes I think this requires some further investigation.

**Pull request closed without merging**
