### PR TITLE
Remove edit project, moved to CPS

### PR DESCRIPTION
**Pull request by jviau**
**Customer scenario**

Edit project file has been moved into CPS to provide this experience for any CPS-based project system. The only behavior change in the CPS move is when a project file is invalid, the invalid file on disk is shown in the editor and not the reverted in-memory file.

This PR removes the related code from this repository. We will need to coordinate a dual insertion of CPS and dotnet project system to avoid any issues with both commands existing at the same time.

**Risk**

Low

**Performance impact**

None

### CODE REVIEW

**Comment by davkean** [comment]
This done for what release? This branch is tracking 15.5.

**Comment by srivatsn** [comment]
The corresponding CPS change is for 15.5 as well.

**Comment by jviau** [comment]
[Associated CPS PR](https://mseng.visualstudio.com/VSIDEProj/_git/VSIDEProj.CPS/pullrequest/234707#_a=overview)

**Comment by jviau** [comment]
@srivatsn I removed `SaveProjectXmlAsync`

**Comment by jviau** [comment]
@srivatsn what branch should we coordinate our insertions into for this?

**Comment by srivatsn** [comment]
we are inserting master in to lab/vsuml. When you are ready to insert the CPS bits, we can merge this change and coordinate an insertion.

**Comment by jviau** [comment]
@srivatsn the CPS PR is merged and insertion build is ready. We can insert to vsuml whenever.

**Comment by srivatsn** [comment]
@jmarolf can you coordinate with @jviau on this?

**Comment by jviau** [comment]
@jmarolf [here is the insertion PR](https://devdiv.visualstudio.com/DevDiv/VS%20IDE%20CPS/_git/VS/pullrequest/77388?_a=overview), Can you complete this PR, and push the .netcore insertion to my branch? Thanks!

**Comment by jmarolf** [comment]
@jviau sure thing.  Thanks!

**Comment by jmarolf** [comment]
@jviau PR is updated and ready to merge.

**Pull request merged**
