### PR TITLE
Bump compiler version

### PR DESCRIPTION
**Pull request by drewnoakes**
Update to newer compiler packages, and fix new warnings.

Pulled out of #9229.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/9242)

### CODE REVIEW

**Review by melytc — APPROVED** [review]

**Review by haileymck — APPROVED** [review]

**Comment by smitpatel** [comment]
I ingested new packages. Some were still missing.

**Comment by adamint** [comment]
We have packages that are > than VS package versions and we need to downgrade.

**Pull request merged**
