### PR TITLE
Move from vside.myget.org to pkgs.dev.azure.com

### PR DESCRIPTION
**Pull request by davidwengier**
Reacting to the impactful change email.

### CODE REVIEW

**Comment by davidwengier** [comment]
Local build passed (after `git clean -xdf`) and I can access the package feed when not on the VPN so if this build green we should be good ¯\\\_(ツ)_/¯

**Comment by davkean** [comment]
To validate these and avoid picking up local packages, you can blow away c:\users\[user]\.nuget\packages.

**Comment by davidwengier** [comment]
> To validate these and avoid picking up local packages, you can blow away c:\users[user].nuget\packages.

Surely the PR build runs on a clean machine, so will validate that? And hopefully not a domain-joined/VPNed machine too.

**Comment by davidwengier** [comment]
Nuked my packages dir, build successfully brought down 744MB of packages 😲

**Comment by drewnoakes** [comment]
👍

**Pull request merged**
