### PR TITLE
Use IVsAsyncFileChangeEx to avoid threadpool exhaustion stalls

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by jmarolf** [comment]
@Pilchie sadly the dependency nonsense you are going to need to resolve is significantly more complex.  Mostly because we consume VS packages that do not correctly declare their dependencies so things will blow up at runtime.

**Comment by Pilchie** [comment]
>@Pilchie sadly the dependency nonsense you are going to need to resolve is significantly more complex. Mostly because we consume VS packages that do not correctly declare their dependencies so things will blow up at runtime.

Yep - have a bunch of assembly reference conflicts that need to be sorted out 😢

**Comment by Pilchie** [comment]
Unit tests at least pass with this set of packages, and there are no more NuGet or Reference version conflicts.

Need to post the set of changed packages to myget though...

**Comment by Pilchie** [comment]
And rebased to deal with @davkean moving my cheese wrt package versions...

**Comment by Pilchie** [comment]
Required packages:

1. Microsoft.VisualStudio.CoreUtility.16.0.28226-alpha.nupkg                                                                                                                                                                                                                                                                                                                             
1. Microsoft.VisualStudio.Diagnostics.PerformanceProvider.16.0.28226-alpha.nupkg                                                                                                                                                                                                                                                                                                         
1. Microsoft.VisualStudio.GraphModel.16.0.28226-alpha.nupkg                                                                                                                                                                                                                                                                                                                              
1. Microsoft.VisualStudio.Shell.Framework.16.0.28226-pre.nupkg                                                                                                                                                                                                                                                                                                                           
1. Microsoft.VisualStudio.Utilities.16.0.28226-pre.nupkg                                                                                                                                                                                                                                                                                                                                 


```

**Comment by davkean** [comment]
@Pilchie Can we merge this as soon as possible so that I can consume this for Razor?

**Comment by Pilchie** [comment]
Yes, want to run VS with the changes at least once, but then will start the approval process.

**Pull request merged**
