### PR TITLE
Fix duplicate order number

### LINKED ISSUE #8708: menu order inconsistent
## Visual Studio Version

17.4.2

## Summary

`Application ` and `Global Usings `  menu order inconsistent

微信截图_20221206155829

image

## Expected Behavior

Be consistent with the menu order in the English language environment

### PR DESCRIPTION
**Pull request by Varorbc**
Fixes #8708

## Before

image

## After

image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8794)

### CODE REVIEW

**Comment by adamint** [comment]
@Varorbc thank you for your contribution. You will need to build the sln then commit, as there are additional generated files from the xaml files you generated.

**Comment by drewnoakes** [comment]
I wonder if we could add a unit test to ensure duplicates don't exist. We have a bunch of similar tests in `RuleTests` (from memory, on a phone).

Don't feel you have to do this as part of the PR.

**Comment by drewnoakes** [comment]
> @adamint Thank you for your suggestion, but I did not find any file to submit after build

I think you only need to do what @adamint is suggesting if you change a localised string value, which hasn't happened here. CI is passing, so we are good.

**Comment by adamint** [comment]
> > @adamint Thank you for your suggestion, but I did not find any file to submit after build
> 
> I think you only need to do what @adamint is suggesting if you change a localised string value, which hasn't happened here. CI is passing, so we are good.

Are you sure about this? I guess when we build locally, the localized xaml files will be updated, but it should really be done here instead. Or am I misunderstanding

**Comment by MiYanni** [comment]
To clarify the localization situation, only certain nodes in XAML files are localized. Those nodes are the [ones seen in this code from xliff-tasks](https://github.com/dotnet/xliff-tasks/blob/09ed469f4a5c3eb72ce585fa1e268e453d13c4fb/src/XliffTasks/Model/XamlRuleDocument.cs#L21-L58). Beyond that, building the project won't change any of the localization files in our repo.

**Comment by adamint** [comment]
I see, my mistake and thank you for the clarifications @smitpatel and @MiYanni. Approved

**Review by adamint — APPROVED** [review]

**Review by melytc — APPROVED** [review]

**Comment by tmeschter** [comment]
To clarify the original issue: the Application and References pages have the same `Order` value. This means that the actual ordering at runtime is undefined, and we end up with differences based on the locale used by the VS UI. To fix this the `Order` value of the References page is increased, which requires increasing the `Order` value of the Build page as well.

**Pull request merged**
