### PR TITLE
Pass analyzers to Roslyn as analyzers

### PR DESCRIPTION
**Pull request by davkean**
In the refactoring we broke analyzers and were passing them as additional files.

tag @dotnet/project-system

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system

**Comment by srivatsn** [comment]
Tagging @MattGertz  for consideration for 15.3 Preview 2

**Customer scenario**
Analyzers won't run in the IDE. This is a regression from a recent change in language service host where we are sending the analyzers as additional files and so for projects that have analyzers, roslyn will think there are no analyzers.

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems?id=443845&fullScreen=false&_a=edit

**Workarounds, if any**

N/A

**Risk**

Low

**Is this a regression from a previous update?**

Yes

**Root cause analysis:**

This was missed when we moved code around to avoid race conditions in the language service. 

**How was the bug found?**

Internal testing

**Comment by srivatsn** [comment]
@davkean can you retarget this to the 15.3.x branch to bring this to Preview2?

**Comment by davkean** [comment]
Ugh, going to need to cherry-pick this, ignore this.

**Comment by srivatsn** [comment]
Why not git rebase -I upstream\dev15.3.x and drop all changes except yours?

**Comment by davkean** [comment]
Was this approved to merge for Preview2?

**Comment by natidea** [comment]
Yes, approved to merge via [443845](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/443845)

**Pull request merged**
