### PR TITLE
fixing tab ordering in debug options page

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes this VS bug: 
- [622505](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/622505)

Fix description:

- Today we do not set the tab ordering for the debug page.  This change sets the first item on the debug page as a place for tab ordering to stop at as well as indicating that it should be first in the tab order

### CODE REVIEW

**Comment by Pilchie** [comment]
I thought that in the absence of explicitly setting it, WPF did it in the order controls appear on the page.  Do we understand why that wasn't the case here?

**Comment by davkean** [comment]
Yeah, that Combo is definitely a TabStop - so I have the same question.

**Comment by jmarolf** [comment]
@Pilchie we want this for 15.8 or master?

**Comment by Pilchie** [comment]
Given the low risk, I'd take to the QB for 15.8 still.

**Comment by jmarolf** [comment]
alright, re targeted.  I'll fill out the ask mode template

**Comment by jmarolf** [comment]
@Pilchie I've updated the [bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/622505) for QB approval

**Comment by Pilchie** [comment]
Approved by QB on Friday - forgot to update the label here.

**Pull request merged**
