### PR TITLE
Remove IVTs to assemblies that no longer exist

### PR DESCRIPTION
**Pull request by sharwell**
Found while reviewing dotnet/roslyn#35070

### CODE REVIEW

**Comment by dmonroym** [comment]
We should also remove these:
https://github.com/dotnet/project-system/blob/cf9d1ae8a31e3b4d99ccfdfc02ca9761a4536977/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj#L15-L16

And perhaps also clean this up https://github.com/dotnet/project-system/blob/cf9d1ae8a31e3b4d99ccfdfc02ca9761a4536977/docs/repo/features.md#L5-L13

**Comment by sharwell** [comment]
@dmonroym I updated this to address you feedback. Please take a look.

**Comment by dmonroym** [comment]
@sharwell we should remove the references here as well:
https://github.com/dotnet/project-system/blob/cf9d1ae8a31e3b4d99ccfdfc02ca9761a4536977/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests/Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests.csproj#L15-L16

**Comment by sharwell** [comment]
@dmonroym 😕 I think they already are? https://github.com/dotnet/project-system/pull/4795/files#diff-9b85e7703f4300c34f96a2e0028edd72

**Comment by dmonroym** [comment]
You're right

**Comment by jmarolf** [comment]
@sharwell feel free to merge

**Pull request merged**
