### PR TITLE
Revert "add xunit analyzers"

### PR DESCRIPTION
**Pull request by jmarolf**
Reverts dotnet/project-system#2619

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@jmarolf May I ask why this has been reverted?

**Comment by jmarolf** [comment]
@ErikSchierboom as per discussion here: https://github.com/dotnet/project-system/pull/2619 this work is being done as part of the massive Repo toolset PR [here](https://github.com/dotnet/project-system/pull/2606)

**Comment by ErikSchierboom** [comment]
@jmarolf Ah okay, thanks! By the way, I saw that you had to [lessen the severity of the X1004 rule](https://github.com/dotnet/project-system/commit/fdbe215ce5e603372b07a48baa6737dbb11d5e36#diff-521f01446f80074cefb6d53b931980fdR30) (about skipped tests). As of yesterday, a [PR](https://github.com/xunit/xunit.analyzers/commit/9469400f8de7d7abd6a4392f5c7048db1444f3bc) has been merged that reduces the severity of this rule to Information (although a new NuGet package hasn't yet been released).

**Comment by marcind** [comment]
FYI, version [0.6.0](https://www.nuget.org/packages/xunit.analyzers/0.6.0) is out with the severity for x1004 reduced to Info.

**Pull request merged**
