### PR TITLE
LOC CHECKIN 20200708 | dotnet-project-system dev16.7.x

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/dotnet/project-system/pull/6349)

### CODE REVIEW

**Comment by wli3** [comment]
@tmeschter could you help me merge this issue and make sure it get inserted to 16.7?

**Comment by tmeschter** [comment]
@wli3 Sure. Do we need an AzDO bug to take for QB approval?

**Comment by tmeschter** [comment]
I went ahead and created https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1154030.

**Comment by wli3** [comment]
looks like we need QB approval all the way to the end. So, ya, let's ask for it

**Comment by wli3** [comment]
Any update?

**Comment by tmeschter** [comment]
@wli3 The change has been merged into dotnet/project-system. Once an insertion PR is generated we will take the bug for approval.

**Pull request merged**
