### PR TITLE
Add option for LangVersion 7.2

### PR DESCRIPTION
**Pull request by jcouv**
Preparing 15.6 branch for language features for C# 7.2.

image

image

Relates to compiler change https://github.com/dotnet/roslyn/pull/19846

FYI @OmarTawfik

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet/project-system for review. Thanks

**Comment by davkean** [comment]
It would be great that we get a service from the Roslyn side so that we don't need to get updating this.

**Comment by jcouv** [comment]
@davkean I agree. This is getting old quickly ;-)
What kind of integration do you have in mind? Is there any integration of this kind that I could mimic?

**Comment by davkean** [comment]
I'm thinking a MEF service that maps from Roslyn's language name to a set of available language versions (with enough data to display and burn it into the project), exposed via the LanguageServices dll you already have.

**Comment by jcouv** [comment]
Do I need a second review, or can I go ahead and merge?

**Comment by OmarTawfik** [comment]
@jcouv @davkean I think the IDE team can provide more information on the MEF implementations. This can be exposed as a workspace service maybe? that gets information from the compiler types/enums.
cc @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
@OmarTawfik Many ways you could do it. I agree that doing it seems like a good idea. :-)

**Comment by davkean** [comment]
@OmarTawfik Does the available languages version change per workspace? If not, then why does it have to be a workspace service?

**Comment by OmarTawfik** [comment]
@davkean NAFAIK. I'm simply asking of where would the ideal location to do this :)

**Comment by jcouv** [comment]
FYI I also added a new LangVersion for VB (15.6) ([PR](https://github.com/dotnet/roslyn/pull/19896)). 

@OmarTawfik This will not have a corresponding project-system change because 
- there is no settings page for LangVer in VB and 
- the passing of LangVer from msbuild to project system in VB has been generalized ([PR](https://github.com/dotnet/roslyn/pull/19112)) when I added VB 15.3

I will make sure to test end-to-end once the first VB 15.6 feature is implemented.

**Comment by jcouv** [comment]
Files https://github.com/dotnet/project-system/issues/3121 for improving this process with an integrated solution.

**Pull request merged**
