### PR TITLE
Various XML doc fixes

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes various issues with XML documentation.

- Add using directives that are required only to resolve symbols in XML docs
- Fixed some references/signatures
- Minor formatting

### CODE REVIEW

**Comment by drewnoakes** [comment]
There was one broken reference I couldn't confidently resolve. In `OnceInitializedOnceDisposedUnderLockAsync.cs` there's an unresolved reference to `ThreadSafeOnceInitializedOnceDisposedAsync` on line 63.

**Comment by drewnoakes** [comment]
@sharwell currently there is no documentation being built.

**Comment by sharwell** [comment]
Looks like the 15.8 compiler fixes the worst issue (dotnet/roslyn#2773). However, if documentation comments are used the solution should really be generating the XML files for all projects or else a bunch of things are just broken.

**Comment by drewnoakes** [comment]
I fixed up a few more errors and added `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to `Directory.Build.props` in the `src` folder.

The only remaining warning is the one I mentioned earlier:

> ProjectSystem\OnceInitializedOnceDisposedUnderLockAsync.cs(63,58,63,100): warning CS1574: XML comment has cref attribute 'ThreadSafeOnceInitializedOnceDisposedAsync' that could not be resolved

Can anyone help with what this should be replaced with?

Do we want to ship the documentation XML anywhere?

**Comment by davkean** [comment]
ThreadSafeOnceInitializedOnceDisposedAsync > OnceInitializedOnceDisposedUnderLockAsync

**Comment by drewnoakes** [comment]
One of the build steps is failing on the XML documentation file. 

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5513,44): error MSB4023: Cannot evaluate the item metadata "%(FullPath)". The item metadata "%(FullPath)" cannot be applied to the path "D:\j\workspace\windows_relea---22c57ed6\artifacts\Release\obj\Microsoft.VisualStudio.AppDesigner\D:\j\workspace\windows_relea---22c57ed6\artifacts\Release\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.xml". The given path's format is not supported. [D:\j\workspace\windows_relea---22c57ed6\src\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj]

In this case, the path of file `Microsoft.VisualStudio.AppDesigner.xml` is being computed as the concatenation of two absolute paths, resulting in the invalid path:

> D:\j\workspace\windows_relea---22c57ed6\artifacts\Release\obj\Microsoft.VisualStudio.AppDesigner\D:\j\workspace\windows_relea---22c57ed6\artifacts\Release\obj\Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.xml

Line 5513 of `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets` on my machine makes no reference to `%(FullPath)` or anything seemingly related.

Any tips on debugging this would be appreciated.

**Comment by Pilchie** [comment]
In general, I recommend taking a look at a binary log from msbuild (`msbuild /bl`) with https://msbuildlog.com.

Also tagging @nguerrera for this particular issue.

**Comment by nguerrera** [comment]
This looks like https://github.com/dotnet/sdk/issues/1598, which would suggest an older SDK (than 2.1.300) is being used in the build. Does this only repro on Jenkins or do you see this too?

**Comment by drewnoakes** [comment]
@Pilchie, thanks, the structured log viewer was helpful.

> This looks like dotnet/sdk#1598, which would suggest an older SDK (than 2.1.300) is being used in the build.

@nguerrera using @Pilchie's viewer I only see references to SDK 2.1.4, such as:

>Property reassignment: $(MSBuildAllProjects)=";C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props;D:\j\workspace\windows_relea---22c57ed6\src\Microsoft.VisualStudio.AppDesigner\Directory.Build.props" (previous value: ";C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.props (33,5)

> Does this only repro on Jenkins or do you see this too?

I can't reproduce this locally. SDK 2.1.402.

**Comment by Pilchie** [comment]
I think this is probably https://github.com/dotnet/project-system/issues/3700 now, where project-system *really* needs to update to something newer.  @jmarolf / @etbyrd  any updates about that?

**Comment by davkean** [comment]
What's currently blocking this?

**Comment by drewnoakes** [comment]
@dotnet-bot test

**Comment by drewnoakes** [comment]
In summary, enabling [`GenerateDocumentationFile`](https://github.com/dotnet/project-system/pull/4036/files#diff-6483fde6c45c90fdfe98ca72eadfa651R21) triggered a bug that's reportedly fixed in a newer version of the SDK. The assumption is that our build uses an older SDK.

We either upgrade the SDK or remove `GenerateDocumentationFile`. I know how to do the latter 😃 

I also cannot repro this locally, and it seems the original builds have been deleted.

**Comment by jmarolf** [comment]
I am going to close and re-open this PR.  Something is weird.

**Comment by drewnoakes** [comment]
Thanks @jmarolf, that produced a [viable build log](https://dnceng.visualstudio.com/public/_build/results?buildId=30952&view=logs).

I'm confused now. The log claims:

> 2018-10-16T15:43:04.4217204Z ProjectSystem\ThreadingExtensions.cs(26,139): error CS1573: Parameter 'cancellationToken' has no matching param tag in the XML comment for 'ThreadingExtensions.SwitchToUIThread(IProjectThreadingService, CancellationToken)' (but other parameters do) [D:\a\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
> 2018-10-16T15:43:04.4218366Z ProjectSystem\ThreadingExtensions.cs(26,139): error CS1573: Parameter 'cancellationToken' has no matching param tag in the XML comment for 'ThreadingExtensions.SwitchToUIThread(IProjectThreadingService, CancellationToken)' (but other parameters do) [D:\a\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]

However we don't have `ThreadingExtensions.cs` anywhere in our tree, afaict. How is this file included in the compilation of `Microsoft.VisualStudio.ProjectSystem.Managed.csproj`?

**Comment by jmarolf** [comment]
Builds are currently failing with this error:

```ini
ProjectSystem\ThreadingExtensions.cs(26,139): error CS1573: Parameter 'cancellationToken' has no matching param tag in the XML comment for 'ThreadingExtensions.SwitchToUIThread(IProjectThreadingService, CancellationToken)' (but other parameters do) [D:\a\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
ProjectSystem\ThreadingExtensions.cs(26,139): error CS1573: Parameter 'cancellationToken' has no matching param tag in the XML comment for 'ThreadingExtensions.SwitchToUIThread(IProjectThreadingService, CancellationToken)' (but other parameters do) [D:\a\1\s\src\Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj]
2018-10-16T15:47:26.4569859Z     0 Warning(s)
2018-10-16T15:47:26.4873585Z     2 Error(s)
```

**Comment by davidwengier** [comment]
> However we don't have `ThreadingExtensions.cs` anywhere in our tree

I've got one 😕 

image

**Comment by davkean** [comment]
Sync to tip.

**Comment by drewnoakes** [comment]
I hadn't considered CI PR builds run _after_ merging with the tip (which makes sense), probably because I generally rebase my PRs in other repos. TIL.

**Comment by davkean** [comment]
Are param arguments required or just when you specify one?

**Comment by drewnoakes** [comment]
It's all or nothing with this change.

**Comment by davkean** [comment]
I'm okay with that, just wanted to confirm.

**Comment by davkean** [comment]
@dotnet-bot retest windows_debug please
@dotnet-bot retest windows_release please

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Comment by davkean** [comment]
@dotnet-bot retest windows_debug please

**Comment by davkean** [comment]
@dotnet-bot retest windows_release please

**Comment by davkean** [comment]
@dotnet-bot test this please

**Comment by drewnoakes** [comment]
@dotnet-bot test this please

**Comment by drewnoakes** [comment]
The test run before this passed. The one I queued timed out. But it does seem that this PR is ok to be merged. I'll do so on Monday unless anyone objects.

**Comment by drewnoakes** [comment]
@dotnet-bot test this please

**Comment by jmarolf** [comment]
👍 	you are good to merge

**Comment by drewnoakes** [comment]
Thanks for all the help getting the environment sorted.

**Pull request merged**
