### PR TITLE
Add Gitter link to README

### PR DESCRIPTION
**Pull request by etbyrd**
This is the correct markdown of https://github.com/dotnet/project-system/pull/3871

### CODE REVIEW

**Comment by etbyrd** [comment]
To be clear: I am not arguing the merits of adding it, just wanted a PR that was correct.

**Comment by etbyrd** [comment]
@Pilchie Should I go ahead and remove the 15.7.x branch?

**Comment by Pilchie** [comment]
Sure, though we should also make sure we have a tag for the bits that shipped in 15.7 (and 15.8) if we haven't yet.  I think @davkean asked @dotnet/roslyn-infrastructure about that the other day.

**Comment by davkean** [comment]
15.7 branch is already gone.

**Pull request merged**
