### PR TITLE
Remove unused usings

### PR DESCRIPTION
**Pull request by davkean**

### CODE REVIEW

**Comment by jmarolf** [comment]
Why don't we have unused usings fail the build?

**Comment by davkean** [comment]
If you can tell me how to do this - that would be great.

**Comment by jmarolf** [comment]
@davkean my mistake I forgot we don't fire these on command-line build. @Pilchie and @sharwell as part of making style warnings work on the commandline are we also going to port unnecessary usings/imports diagnostics?

**Comment by sharwell** [comment]
@jmarolf Eventually they'll all be moved over (or as many as possible) but the order could vary.

**Pull request merged**
