### PR TITLE
Add a link to show the new Launch Profile UI

### PR DESCRIPTION
**Pull request by drewnoakes**
This PR adds a link action that invokes a command in CPS to show the new Launch Profile UI. The link is displayed on the "Debug" page of the new Project Properties UI.

Sibling CPS PR (Internal): https://devdiv.visualstudio.com/DevDiv/_git/CPS/pullrequest/310621

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/7023)

### CODE REVIEW

**Review by tmeschter — APPROVED** [review]

**Comment by tmeschter** [comment]
@drewnoakes Do we still need to get this in to enable launch profiles?

**Review by dmonroym — APPROVED** [review]

**Review by jjmew — APPROVED** [review]
:shipit:

**Comment by miloush** [comment]
When I click the link in 16.10 Preview 2.1, I get an error message box:

image

Is that expected? Is there another way to get to the dialog? I would like to launch the app with an argument.

**Comment by drewnoakes** [comment]
@miloush thank you for taking the time to provide this feedback. This bug was caused by one component that was not updated in time for the preview you are using. Newer previews will resolve this.

**Pull request merged**
