### PR TITLE
Delete translated xaml files that are now generated by the build

### PR DESCRIPTION
**Pull request by nguerrera**
xliff-tasks now generates the translated files during the build to the intermediate directory, but there are stale copies of translated rule files still checked in.

**Customer scenario**

None, this is infrastructure-only. 

There are dangling files that are unused and out-of-date that can only cause confusion for project-system developers and the loc champ.

**Bugs this fixes:** 

N/A

**Workarounds, if any**

N/A

**Risk**

Low, this just deletes unused files.

**Performance impact**

None, this just deletes unused files.

**Is this a regression from a previous update?**

N/A

**Root cause analysis:**

Missed cleanup step in conversion to repo toolset / xliff-tasks. The checked in translated resx and vsct files were deleted, but not the translated xaml rules.

**How was the bug found?**

Code inspection

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@nguerrera That branch now exists if you want it.

**Comment by nguerrera** [comment]
@Pilchie retargeted to post-dev15.5. Is that the right branch?

**Comment by Pilchie** [comment]
Yes.  Thanks @nguerrera

**Comment by nguerrera** [comment]
Merge?

**Comment by Pilchie** [comment]
Yep

**Pull request merged**
