### PR TITLE
Include capabilities in project subscription dataflow

### PR DESCRIPTION
**Pull request by BillHiebert**
This addresses the issue described in DEVDIV [553720](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=553720)

Basically, when first reading the launch settings files in response to dataflow, the AspNetCoreWeb is not present which breaks the launch settings provider which imports custom serializers. This is similar to the other race conditions that been reported recently with capabilities not being present when responding to dataflow. The fix is to include the capabilities dataflow in the project subscription in a manner similar to this [PR](https://github.com/dotnet/project-system/pull/3167).

In addition to the above, I was concerned about capabilities changing even when nothing in the project subscription has changed.  The project rule dataflow change handler only looks at the ActiveDebugProfile property and would miss the capabilities only change. To address this I created a separate dataflow block to handle that.

**Risk**
The risk should be low as other than adding the new capability handler the core code didn't change at all. 

**Performance impact**
Shouldn't be any.

**Is this a regression from a previous update?**
Yes.

**Root cause analysis:**
Appears to be related to a change in when capabilities evaluated from msbuild are completed in CPS

**How was the bug found?**
AdHoc and signoff testing

### CODE REVIEW

**Comment by Pilchie** [comment]
Should we take this as part of @natidea's change for Preview 3 to address all of these at once?

**Comment by natidea** [comment]
@Pilchie I'm not sure how common the scenario is. @BillHiebert is this urgent enough for Preview 3, or can it wait for Preview 4?

**Comment by natidea** [comment]
I've prepared a signed build with my changes for Vendors already.

**Comment by BillHiebert** [comment]
@natidea, @Pilchie  - the bug was triage for preview 4 so we can wait until then.

**Pull request merged**
