### PR TITLE
Delete references to IDE dispose analyzers

### PR DESCRIPTION
**Pull request by xtqqczze**
The IDE dispose analyzer rules have been deleted from Roslyn:

https://github.com/dotnet/roslyn/commit/eeba499ecf839ec35bca25062d69d2fc5c4885b9

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/7403)

### CODE REVIEW

**Comment by xtqqczze** [comment]
See also: https://github.com/dotnet/runtime/commit/ca3b27963931172f0535fff644e1fae23f406193

**Comment by xtqqczze** [comment]
The suppressions of `IDE0069` should be replaced with suppressions of [CA2213: Disposable fields should be disposed](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2213)

**Comment by xtqqczze** [comment]
The suppressions of `IDE0068` should be replaced with suppressions of [CA2000: Dispose objects before losing scope](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2200)?

**Comment by drewnoakes** [comment]
@xtqqczze are you happy with this PR?

Do you see any diagnostics in files after removing the suppressions?

**Comment by MiYanni** [comment]
I've updated the branch and removed the suggested suppressions. They only existed for the .editorconfig of the tests. No warnings on build. I leafed through the files to see if those warnings where there, and didn't see them in the files I checked. This PR looks good to go.

**Review by MiYanni — APPROVED** [review]

**Comment by xtqqczze** [comment]
My concern is that the `SuppressMessage` attributes were possibly added for a good reason (by @davkean in #6256), therefore we should keep these suppressions, but change the diagnostic identifiers to `CA2000`, `CA2213`, etc.

**Comment by MiYanni** [comment]
@xtqqczze I don't see any code changes related to that issue. I see from the original ticket here (https://developercommunity.visualstudio.com/t/vs-2019-1650-hangs-when-opening-a-project-where-a-1/954681) that the issue has been resolved. But from the internal ticket, there is no link to the actual PR. 

Either way, the suppressions shouldn't affect the product's logic in any way. It would only affect building it, right? I specifically checked this one and there was no difference between the suppression existing versus not existing: `~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.WndProc(System.Windows.Forms.Message@)`. I don't believe that removing these suppressions will cause harm.

**Comment by drewnoakes** [comment]
The only downside to the suppressions would be getting a bunch of diagnostics during build (or in the IDE). If we don't see those, then it's fine to remove them.

**Comment by drewnoakes** [comment]
Let's merge this. It builds cleanly and can be tweaked if needed. Thanks very much @xtqqczze.

**Comment by xtqqczze** [comment]
> @xtqqczze I don't see any code changes related to that issue. I see from the original ticket here (https://developercommunity.visualstudio.com/t/vs-2019-1650-hangs-when-opening-a-project-where-a-1/954681) that the issue has been resolved. But from the internal ticket, there is no link to the actual PR.

I'm not sure how I came to link to that issue, I was thinking of #5019.
#5019

**Pull request merged**
