### PR TITLE
Fix VS consumes large amount of CPU 

### PR DESCRIPTION
**Pull request by davkean**
**Customer scenario**

Certain projects consumes large amount of CPU while the project is open.

There are many ways to represent a "friendly name" of a target framework in the `<TargetFrameworks>` element. For example, .NET Framework 4.0, can be represented as:

``` XML
<TargetFrameworks>net4</TargetFrameworks>
```
-or-

``` XML
<TargetFrameworks>net4.0</TargetFrameworks>
```

-or-

``` XML
<TargetFrameworks>net40</TargetFrameworks>
```

If you enter a form that is not canonical from what we get from NuGet (ie the first two), we continually process data forever, consuming larges amounts of CPU. 

**Bugs this fixes:** 

Fixes https://github.com/dotnet/project-system/issues/2388

**Workarounds, if any**

Change the element to be in the canonical form. It is not obvious this is the cause.

**Risk**

Low

**Performance impact**

None - we're effectively pulling a name from a cache.

**Is this a regression from a previous update?**

Yes, from 15.2.

**Root cause analysis:**

We have internal guidance not to parse or reason able these values, which we consider to be "user written" - but this was overlooked in this case. Right now the smallest, least risky change was made, but in the future (int #2525) we're centralizing all understanding of this error prone code in a single location.

**How was the bug found?**

Customer reported. We have external reports that I've yet to verify if they have the same underlying cause.

**Dev Notes**

We were making the assumption that the literal user written short name, matched the canonical version of the short name. This wasn't the case:

The project file had:

    portable-net4+win8+wpa81

Our "canonical" version had:

    portable-net40+win8+wpa81

This was causing us to continually reset our subscriptions to the data flow, and constantly process the same data over and over again.

After my fix, we still do not handle the portable versions correctly in the project, in that we only show one of them in the dependencies tree, filed #2524 to track that. I've confirmed this this wasn't regressed in this change.

Note also that this code shouldn't even be looking at TFMs, filed: #2525 to track that.

### CODE REVIEW

**Comment by srivatsn** [comment]
Tagging @MattGertz for Preview4

**Comment by davkean** [comment]
@natidea Do you mean it also needs to be fixed in the language service?

**Comment by natidea** [comment]
@davkean I don't know if the language service can end up in the same state (presumably not if the CPU hog is gone), but it has an identical clone of this method: [HasMatchingTargetFrameworks](https://github.com/dotnet/project-system/blob/49346868655624feceb1cd1143727201fd9b07f5/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/LanguageServices/AggregateWorkspaceProjectContext.cs#L102)

**Comment by davkean** [comment]
Nice catch, let me investigate that.

**Comment by davkean** [comment]
Forgot that the dependency node basically forked the same code from the language service.

It doesn't suffer from the same problem - it's just comparing the exact value it retrieved previously without canonicalizing it. So while it will reset unnecessarily if the user changed net40 -> net4.0 - it doesn't continuously reset.

**Comment by davkean** [comment]
Remember folks:
> - DO NOT parse or attempt to reason about the values of properties that make up the dimensions for a project configuration; $(Configuration), $(Platform) and $(TargetFramework), and their plural counterparts; $(Configurations), $(Platforms) and $(TargetFrameworks).
> These properties are user "aliases" and should only be used for conditions, display and grouping purposes. Instead, the project system should be using their canonical equivalents; $(PlatformTarget) instead of $(Platform), and $(TargetFrameworkMoniker) instead of $(TargetFramework).

**Pull request merged**
