### PR TITLE
Enable CodeQL 3000

### PR DESCRIPTION
**Pull request by MiYanni**
Resolves: https://github.com/dotnet/project-system/issues/8421

[CodeQL](https://github.com/github/codeql) is an analysis tool for vulnerabilities. This PR is enabling a version of a CodeQL AzDO task called [CodeQL 3000](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines). There is another CodeQL task created by Guardian (same set of tools for the rest of our compliance checks), but this is not that task. This CodeQL task is auto-injected into the pipeline (a dynamic task that is not directly declared in the pipeline YML).

Unfortunately, I cannot directly test the auto-injected run of this task. [According to the documentation](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/configuring-codeql3000-ado-pipelines#how-does-this-extension-work), the auto-injected task only runs on the default branch for the repo (aka. `main` for us). I tested CodeQL 3000 using the manually added Init/Finalize tasks: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6722796&view=logs&j=3de96e8d-b8d1-5108-47b8-f6a54739db67&t=f9aea6eb-8f15-55f4-c13f-b9d7005edfde

This test run added *3 mins* to our Build job time, but that seems reasonable over the alternative. The alternative is using the [Guardian CodeQL task](https://eng.ms/docs/security-compliance-identity-and-management-scim/security/azure-security/cloudai-security-fundamentals-engineering/security-integration/guardian-wiki/sdl-azdo-extension/codeql-build-task) which requires a **rebuild of the code** to run the analysis. While this would run in parallel with other compliance jobs, it is extra work for the job agents that is not necessary. Also, there was an issue with that task where it seems to be running the wrong version of .NET, which causes it to not build properly. I feel that the CodeQL 3000 task is a fair compromise comparatively to the Guardian CodeQL task.

After this is merged and I see the actual auto-injected task runs, I'll make a follow-up PR that removes the current `analyze-vulnerabilities.yml` I added for using the Guardian CodeQL task (but doesn't run because of the build issue described).

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/project-system/pull/8516)

### CODE REVIEW

**Review by kvenkatrajan — APPROVED** [review]

**Comment by tmeschter** [comment]
Is there something we can check in the logs to verify that CodeQL is running?

**Comment by MiYanni** [comment]
@tmeschter Yes. It will look like this:
image
(an example image from the CodeQL3K docs)

**Comment by MiYanni** [comment]
After merging this PR, the process is working as expected:
image
image

**Comment by MiYanni** [comment]
Another note for CodeQL 3000 is that it auto-limits itself from running. If there is a recent scan, it won't run a new scan.
image

**Pull request merged**
