### PR TITLE
Make IActiveConfiguredProjectsProvider public

### PR DESCRIPTION
**Pull request by davkean**
VSTest would like to consumer this interface, make it public.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/project-system @rahulpaw

**Comment by srivatsn** [comment]
What's holding up this PR?

**Comment by davkean** [comment]
@tannergooding Yes we should be, I've been meaning to add it for a while, but haven't had time.

**Comment by rahulpaw** [comment]
adding a DEVDIV bug: https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_workitems?id=441165

**Comment by srivatsn** [comment]
What are we waiting on for merging this? That it is really needed for the test scenario? @rahulpaw - can you confirm? Can you also test with this API to make sure it addresses all your needs?

**Comment by davkean** [comment]
@srivatsn Yes, I've held off merging because @rahulpaw was off working on something else, and I wanted to avoid merging an API that I know isn't good enough for us (we need to support dataflow for the new error list component we need to write).

**Comment by rahulpaw** [comment]
This is needed to support the Multi TFM scenarios for Test Tools. Without this, we don't get the list of active configured projects.

**Comment by srivatsn** [comment]
Tagging @MattGertz  for approval - this makes a type public that's needed by test explorer to support running tests for multiple TFMs.

**Comment by davkean** [comment]
@rahulpaw I'm going to close this without merging in - please reach out to me in 15.6 after you've verified that this works for you.

**Pull request closed without merging**
