### PR TITLE
Import props/targets from NuGet in WPF tmpproj builds

### PR DESCRIPTION
**Pull request by Pilchie**
Thanks @tmat for the inspiration.

### CODE REVIEW

**Comment by Pilchie** [comment]
Confirmed with a binlog that this seems to work

**Comment by davkean** [comment]
@Pilchie Does affect PackageReference in legacy as well? We should get a bug to fix this also in MSBuild/SDK.

**Comment by Pilchie** [comment]
Yes, and there is already bug on MSBuild to fix it.

**Comment by Pilchie** [comment]
This seems to not be working on the build machines after all.  I'll have to investigate further :(

**Comment by davkean** [comment]
Didn't the project name change between .NET versions just recently?

**Comment by nguerrera** [comment]
> Didn't the project name change between .NET versions just recently?

Yes

**Comment by Pilchie** [comment]
Ah, maybe the build machines don't have a new enough .NET Framework?  This was a change in the runtime, and not the targeting pack, right?

**Comment by nguerrera** [comment]
> This was a change in the runtime, and not the targeting pack, right?

Correct.

**Comment by Pilchie** [comment]
Maybe the issue is that the build machines in CI aren't running `net472`?  If so, that sounds like a problem waiting to happen, since we've updated this project to target `net472`, so tests could fail at any time in the future.  @jmarolf do you know if we do/can require `net472` for CI builds?

**Comment by Pilchie** [comment]
Nevermind - seems problem is our old version of repo toolset.  `_IsWpfTempProject` is `true`, but `_WpfTempProjectNuGetFileNameNoExt` isn't getting the right path to the artifacts directory.

**Pull request merged**
