### PR TITLE
Upgrade C# version to 7.2

### PR DESCRIPTION
**Pull request by davkean**

### CODE REVIEW

**Comment by Pilchie** [comment]
Need to update the version of the compiler package too.

**Comment by davkean** [comment]
Ah, don't want compiler package as it slows down builds significantly. Trying 7.2.

**Comment by davkean** [comment]
Nope give up on that, we don't have 15.5 on build machines - @jasonmalinowski is this on the radar?

**Comment by davkean** [comment]
Nevermind, I see latest-dev15-5 does this.

**Comment by tannergooding** [comment]
@davkean, try the `Windows.10.Amd64.ClientRS4.DevEx.Open` image.

**Comment by davkean** [comment]
@tannergooding What does that have on it?

**Comment by davkean** [comment]
We resolved offline, going to leave on 15.5 https://github.com/dotnet/project-system/pull/3597 to avoid accidental dependencies on 15.7.

**Pull request merged**
